// Kronologi Lotara — document data & helpers
// Plain JS — no TypeScript, no type errors

const MONTHS_MAP={januari:1,februari:2,maret:3,april:4,mei:5,juni:6,juli:7,agustus:8,september:9,oktober:10,november:11,desember:12,nopember:11};

function parseDateKey(d){
  if(!d)return 0;
  const s=d.trim();
  const m1=s.match(/^(\d{1,2})\s+(\w+)\s+(\d{4})$/i);
  if(m1){const mo=MONTHS_MAP[m1[2].toLowerCase()]||0;return parseInt(m1[3])*10000+mo*100+parseInt(m1[1]);}
  const m2=s.match(/^(\w+)\s+(\d{4})$/i);
  if(m2){const mo=MONTHS_MAP[m2[1].toLowerCase()]||0;return parseInt(m2[2])*10000+mo*100+1;}
  const m3=s.match(/^(\d{4})$/);
  if(m3){return parseInt(m3[1])*10000+1*100+1;}
  return 0;
}

function getYear(d){if(!d)return null;const k=parseDateKey(d);return k>0?Math.floor(k/10000):null;}

const CAT_LABELS={
  surat:'Surat',
  perizinan:'Perizinan',
  kontrak:'Kontrak',
  'berita-acara':'Berita Acara',
  laporan:'Laporan',
  undangan:'Undangan',
  hukum:'Hukum / Teguran'
};

function categorize(perihal){
  const p=(perihal||'').toLowerCase();
  if(p.includes('undangan')) return 'undangan';
  if(p.includes('berita acara')) return 'berita-acara';
  if(p.includes('perjanjian kerjasama')||p.includes('perjanjian kerja sama')||p.includes('kontrak')||p.includes('addendum')||p.includes('penandatanganan perjanjian')||p.includes('restrukturisasi kerjasama')||p.includes('restrukturisasi kerja sama')) return 'kontrak';
  if(p.includes('izin')||p.includes('perizinan')||p.includes('persetujuan kerjasama')||p.includes('persetujuan kerja sama')||p.includes('penetapan badan')||p.includes('rekomendasi')||p.includes('kualifikasi')||p.includes('tagihan')||p.includes('garansi bank')||p.includes('bukti penerimaan')||p.includes('tanda terima dokumen')||p.includes('tanda terima permohonan')||p.includes('penerimaan negara')||p.includes('penetapan izin')||p.includes('pemberian izin')||p.includes('penerbitan izin')||p.includes('pkkprl')) return 'perizinan';
  if(p.includes('laporan')||p.includes('evaluasi')||p.includes('hasil review')||p.includes('review')||p.includes('notulen')||p.includes('hasil rapat')||p.includes('laporan kajian')||p.includes('kajian')||p.includes('laporan hasil')||p.includes('laporan proyek')) return 'laporan';
  if(p.includes('pengaduan')||p.includes('peringatan')||p.includes('teguran')||p.includes('permintaan keterangan')||p.includes('klarifikasi')||p.includes('tanggapan pembatalan')||p.includes('penghentian pelanggaran')||p.includes('laporan dugaan')||p.includes('permintaan dokumen')||p.includes('penyelidikan')) return 'hukum';
  return 'surat';
}

const DOCS = [
  // ── 2016 ──
  {id:'a1',tanggal:'09 Juni 2016',nomor_surat:'021/TIARA/VI/2016',perihal:'Permohonan Presentasi',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana mengajukan permohonan presentasi kepada Direktur Utama PDAM Kabupaten Lombok Utara. Surat menawarkan kerja sama terkait pengolahan dan penyediaan air minum menggunakan teknologi Sea Water Reverse Osmosis (SWRO). Ditandatangani oleh I Made Gde Putra Yasa selaku Direktur, 9 Juni 2016.'},
  {id:'a2',tanggal:'13 Juni 2016',nomor_surat:'539.521/PDAM-KLU/VI/2016',perihal:'Undangan Presentasi Teknologi RO',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara mengundang Direktur PT. Tiara Cipta Nirwana untuk presentasi terkait penyediaan dan pengolahan air minum. Pertemuan dijadwalkan Selasa, 21 Juni 2016, pukul 09.00 WITA di Kantor Pusat PDAM. Tindak lanjut atas permohonan presentasi PT. Tiara Cipta Nirwana No. 021/TIARA/VI/2016. Ditandatangani Direktur H. Suhaily, ST.'},
  {id:'a3',tanggal:'21 Juni 2016',nomor_surat:'-',perihal:'Presentasi Desalinasi Air Laut',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Materi presentasi Divisi Water Management PT. Tiara Cipta Nirwana mengenai solusi penyediaan air tawar melalui desalinasi. Teknologi Reverse Osmosis diusulkan untuk mengubah air laut menjadi air tawar di kawasan pariwisata Lombok Utara, khususnya Tiga Gili. Dokumen menyertakan visualisasi peralatan industri dan lokasi target proyek.'},
  {id:'a4',tanggal:'11 Juli 2016',nomor_surat:'11/TIARA/VII/2016',perihal:'Penawaran Kerjasama KPBU Desalinasi',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana mengajukan penawaran kerjasama kepada PDAM Lombok Utara terkait pengolahan air laut dengan teknologi Reverse Osmosis. Latar belakang: meningkatnya kebutuhan air di Gili Air, Gili Meno, dan Gili Trawangan. Skema yang diusulkan adalah KPBU sesuai Perpres No. 38 Tahun 2015. Disertai dokumen Prastudy Kelayakan Proyek sebagai lampiran.'},
  {id:'a5',tanggal:'14 September 2016',nomor_surat:'538.73A/PDAM.KLU/IX/2016',perihal:'Permohonan Persetujuan KPBU',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara mengajukan permohonan persetujuan kepada Bupati Lombok Utara untuk mengadakan KPBU. Permohonan dalam rangka penyediaan air bersih layak minum melalui desalinasi air laut dengan teknologi Reverse Osmosis di wilayah Gili Matra (Gili Air, Gili Meno, Gili Trawangan). Merupakan prakarsa badan usaha (unsolicited). Ditandatangani H. Suhaily, ST.'},
  {id:'a6',tanggal:'16 September 2016',nomor_surat:'690/629/BUP/2016',perihal:'Persetujuan Kerjasama Pemerintah dengan Badan Usaha (KPBU)',pengirim:'Bupati Lombok Utara',ringkasan:'Bupati Lombok Utara memberikan persetujuan kepada PDAM Kabupaten Lombok Utara untuk melaksanakan KPBU penyediaan air bersih layak minum melalui desalinasi air laut teknologi Reverse Osmosis. PDAM Kabupaten Lombok Utara ditetapkan sebagai Penanggung Jawab Proyek Kerjasama (PJPK). Pelaksanaan wajib mematuhi tata cara KPBU atas prakarsa badan usaha.'},
  // ── 2017 ──
  {id:'b1',tanggal:'03 November 2017',nomor_surat:'539.107/PDAM-KLU/XI/2017',perihal:'Permohonan Sosialisasi dan Pendampingan KPBU',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan kepada Direktur Bina Investasi Infrastruktur Kementerian PUPR untuk sosialisasi dan pendampingan terkait rencana pembentukan KPBU Unsolicited bidang SPAM. Dijadwalkan Selasa, 7 November 2017 di Santosa Villas & Resort, Senggigi, mulai pukul 13.30 WITA. Ditandatangani Direktur PDAM R. Waliadin, SE.'},
  {id:'b2',tanggal:'03 November 2017',nomor_surat:'005/234/BUP/2017',perihal:'Undangan Sosialisasi KPBU Ditjen Bina Konstruksi',pengirim:'Bupati Lombok Utara',ringkasan:'Bupati Lombok Utara mengundang pihak terkait dalam acara Sosialisasi KPBU oleh Ditjen Bina Konstruksi Kementerian PUPR. Kegiatan Selasa, 7 November 2017, pukul 13.30 WITA di The Santosa Villas & Resort, Jalan Raya Senggigi. Ditandatangani Dr. H. Najmul Akhyar, SH. MH.'},
  {id:'b3',tanggal:'04 November 2017',nomor_surat:'01/TIARA/XI/2017',perihal:'Permohonan Presentasi SWRO',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. TIARA CIPTA NIRWANA mengajukan permohonan presentasi kepada Direktur Utama PDAM Kab. Lombok Utara mengenai teknologi pengolahan air minum. Menawarkan kerjasama penyediaan air minum menggunakan teknologi Sea Water Reverse Osmosis (SWRO) untuk menunjang kinerja PDAM. Bertanggal 4 November 2017.'},
  {id:'b4',tanggal:'07 November 2017',nomor_surat:'-',perihal:'Berita Acara Pendampingan Penyiapan Proyek KPBU',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Berita acara kegiatan pendampingan penyiapan proyek KPBU unsolicited untuk SPAM Kabupaten Lombok Utara, 7 November 2017. Dihadiri perwakilan Kementerian PUPR, PDAM Lombok Utara, dan PT Tiara Cipta Nirwana. Pembahasan mencakup regulasi KPBU (Perpres No. 38 Tahun 2015) dan aspek teknis pengolahan air laut menghasilkan 40% air tawar. Terdapat perhatian terhadap dampak lingkungan pada ekosistem terumbu karang di kawasan konservasi Gili Matra.'},
  {id:'b5',tanggal:'07 November 2017',nomor_surat:'/TIARA/XI/2017',perihal:'Penawaran Kerjasama Desalinasi',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana mengajukan penawaran kerjasama kepada PDAM untuk penyediaan air minum melalui teknologi desalinasi air laut Reverse Osmosis. Ditujukan untuk kawasan wisata Gili Air, Meno, dan Trawangan, total luas wilayah sekitar 2.954 ha. Usulan mencakup kajian komprehensif dari kelayakan teknis hingga analisis sosial dengan skema KPBU.'},
  {id:'b6',tanggal:'08 November 2017',nomor_surat:'539.108/PDAM-KLU/XI/2017',perihal:'Permohonan Persetujuan Kerjasama Pemerintah dengan Badan Usaha',pengirim:'Direktur PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan persetujuan dari Direktur PDAM Kabupaten Lombok Utara kepada Bupati Lombok Utara untuk mengadakan KPBU penyediaan air bersih layak minum. Dilatarbelakangi kebutuhan air mendesak di wilayah Gili Matra. Skema unsolicited (prakarsa badan usaha) menggunakan teknologi desalinasi Reverse Osmosis. Ditandatangani Raden Waliadin, SE.'},
  {id:'b7',tanggal:'17 November 2017',nomor_surat:'539.111/PDAM-KLU/XI/2017',perihal:'Permohonan Izin dan Pendampingan Survei',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan izin dan pendampingan kepada Kepala Dinas Kebudayaan dan Pariwisata untuk survei kemauan dan kemampuan membayar calon pelanggan di Gili Matra. Terkait proyek KPBU penyediaan infrastruktur air bersih. Survei dijadwalkan mulai 17 November 2017. Ditandatangani Raden Waliadin, SE.'},
  {id:'b8',tanggal:'17 November 2017',nomor_surat:'455/506/BUDPAR/2017',perihal:'Rekomendasi Izin dan Pendampingan Survei',pengirim:'Dinas Kebudayaan dan Pariwisata Kabupaten Lombok Utara',ringkasan:'Dinas Kebudayaan dan Pariwisata memberikan rekomendasi untuk melaksanakan survei kemauan dan kemampuan membayar bagi calon pelanggan PDAM di kawasan Gili MATRA. Kepala Bidang Pengembangan Destinasi dan Usaha Pariwisata ditugaskan sebagai pendamping selama survei berlangsung. Tindak lanjut atas permohonan PDAM tertanggal 17 November 2017.'},
  {id:'b9',tanggal:'17 November 2017',nomor_surat:'539.112/PDAM-KLU/XI/2017',perihal:'Permohonan Izin Sumur Bor',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan izin sumur bor di wilayah Gili Matra (Trawangan, Meno, Air) untuk meningkatkan layanan air bersih dan mendukung pariwisata. Diajukan sesuai Perpres No. 38 Tahun 2015 dalam rangka KPBU. Ditandatangani Raden Waliadin, SE. Tembusan dikirimkan kepada tujuh instansi terkait.'},
  {id:'b10',tanggal:'19 November 2017',nomor_surat:'01/TK-KI KLU/11/2017',perihal:'Laporan Hasil Review Pra Studi Kelayakan',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Laporan hasil review atas dokumen Pra Studi Kelayakan (Pra-FS) proyek KPBU pengolahan air laut oleh PT. Tiara Cipta Nirwana. Tim merekomendasikan proyek dilanjutkan ke tahap Studi Kelayakan dengan catatan mengakomodasi hasil review. Dokumen Pra-FS belum sepenuhnya memenuhi syarat sesuai Pasal 23 UU BAPPENAS, terutama terkait dukungan pemerintah, kajian risiko, dan sinkronisasi regulasi.'},
  {id:'b11',tanggal:'19 November 2017',nomor_surat:'01/PJPK/XI/2017',perihal:'Penetapan Calon Pemrakarsa KPBU',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Surat penetapan PT. Tiara Cipta Nirwana sebagai Calon Pemrakarsa KPBU terkait penyediaan air minum melalui desalinasi air laut. PDAM memberikan persetujuan prinsip atas penggunaan teknologi Reverse Osmosis. Perusahaan wajib menyiapkan Studi Kelayakan dalam waktu paling lambat 6 bulan. Ditandatangani Raden Waliadin, SE.'},
  {id:'b12',tanggal:'20 November 2017',nomor_surat:'539.113/PDAM-KLU/XI/2017',perihal:'Persetujuan Melanjutkan ke Studi Kelayakan',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Surat resmi PDAM Kabupaten Lombok Utara memberikan persetujuan kepada PT. Tiara Cipta Nirwana untuk melanjutkan proyek ke tahap Studi Kelayakan (FS). Berdasarkan tinjauan mendalam terhadap Pra FS oleh Tim Pengkaji Investasi mengenai penyediaan air minum melalui teknologi desalinasi air laut. Ditandatangani Direktur PDAM KLU, Raden Waliadin, SE.'},
  {id:'b13',tanggal:'November 2017',nomor_surat:'-',perihal:'Studi Kelayakan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Laporan studi kelayakan pembangunan sistem desalinasi air laut di Kabupaten Lombok Utara menggunakan teknologi Sea Water Reverse Osmosis (SWRO). Disusun sebagai landasan ilmiah perencanaan air bersih. Analisis mencakup aspek teknis, legalitas skema KPBU, dampak sosial ekonomi, dan analisis keputusan investasi. Dokumen menyertakan rincian biaya operasional, estimasi laba rugi, dan perhitungan arus kas.'},
  {id:'b14',tanggal:'23 November 2017',nomor_surat:'546/2098/DESDM/2017',perihal:'Permohonan Izin Pengeboran',pengirim:'Kepala Dinas ESDM Provinsi NTB',ringkasan:'Surat menanggapi permohonan izin sumur bor di Gili Matra oleh PDAM Lombok Utara tertanggal 17 November 2017. Sesuai Pergub NTB No. 20 Tahun 2013, perizinan pengeboran harus diajukan kepada Gubernur melalui DPMPTSP NTB. Dinas ESDM berfungsi sebagai SKPD teknis yang memberikan pertimbangan teknis. Ditandatangani Ir. Muhammad Husni, M.Si.'},
  {id:'b15',tanggal:'04 Desember 2017',nomor_surat:'539.115/PDAM-KLU/XII/2017',perihal:'Undangan Expose Feasibility Study',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Undangan untuk menghadiri acara Expose Feasibility Study terkait KPBU bidang SPAM. Kegiatan dijadwalkan Selasa, 5 Desember 2017 pukul 09.00 WITA di Hotel Bay Marina Medana Tanjung. Ditandatangani Direktur PDAM Raden Waliadin, SE.'},
  {id:'b16',tanggal:'05 Desember 2017',nomor_surat:'-',perihal:'Berita Acara Expose Feasibility Study',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Berita Acara Expose Feasibility Study mengenai rencana kerjasama pengolahan air laut menjadi air minum di Gili Indah, 5 Desember 2017. PT Tiara Cipta Nirwana menawarkan investasi 30 tahun dengan teknologi osmosis menghasilkan 40% air tawar. Diskusi menekankan kepatuhan regulasi kerjasama unsolicited dan analisis dampak lingkungan. Proyek dianggap mendesak mengatasi keterbatasan air baku di sektor pariwisata.'},
  {id:'b17',tanggal:'05 Desember 2017',nomor_surat:'-',perihal:'Hasil Review Studi Kelayakan',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Hasil tinjauan terhadap studi kelayakan proyek SWRO di Gili Trawangan sebagai proyek percontohan. Poin penyempurnaan mencakup aspek lingkungan, pemetaan kewenangan pemangku kepentingan, dan kejelasan skema KPBU. Tim menekankan pentingnya analisis risiko bisnis dan analisis penghematan ekonomi bagi masyarakat.'},
  {id:'b18',tanggal:'08 Desember 2017',nomor_surat:'02/TK-KI KLU/12/2017',perihal:'Laporan Hasil Review Studi Kelayakan',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Hasil tinjauan Tim Pengkaji terhadap Studi Kelayakan proyek pengolahan air laut di Lombok Utara. Catatan perbaikan meliputi aspek lingkungan Gili Trawangan, dampak sosial ekonomi, skema KPBU, dan analisis risiko. Tim merekomendasikan PT. Tiara Cipta Nirwana diberikan kesempatan melanjutkan sebagai pemrakarsa setelah menyempurnakan studi. Ditandatangani tujuh anggota tim ahli.'},
  {id:'b19',tanggal:'11 Desember 2017',nomor_surat:'539.120/PDAM-KLU/XII/2017',perihal:'Penyampaian Laporan Hasil Review PDAM',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Surat menyampaikan laporan hasil review atas studi kelayakan PT. Tiara Cipta Nirwana. Berdasarkan review Tim Pengkaji No. 02/TK-KI KLU/12/2017, masih terdapat beberapa hal yang perlu disempurnakan. Penyempurnaan diperlukan agar perusahaan dapat ditetapkan sebagai Badan Usaha Pemrakarsa. Ditandatangani Direktur Raden Waliadin, SE.'},
  {id:'b20',tanggal:'12 Desember 2017',nomor_surat:'347.3/TIARA/XII/2017',perihal:'Penyampaian Revisi Studi Kelayakan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana menyampaikan revisi dokumen Studi Kelayakan kepada Direktur PDAM Lombok Utara sebagai tindak lanjut atas surat tinjauan tertanggal 11 Desember 2017. Proyek berfokus pada kerjasama penyediaan air minum melalui teknologi SWRO skema KPBU. Satu set dokumen penyempurnaan dilampirkan.'},
  {id:'b21',tanggal:'13 Desember 2017',nomor_surat:'03/TK-KI KLU/12/2017',perihal:'Laporan Hasil Review Kedua dan Rekomendasi',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Tim Pengkaji merekomendasikan PT. Tiara Cipta Nirwana layak menjadi pemrakarsa KPBU dengan perolehan nilai FS sebesar 10. Evaluasi didasarkan pada presentasi 7 November 2017 dan ekspose 5 Desember 2017. Laporan menekankan sinkronisasi regulasi antar tingkat pemerintahan untuk Gili Trawangan sebagai pilot project.'},
  {id:'b22',tanggal:'13 Desember 2017',nomor_surat:'02/PJPK/XII/2017',perihal:'Penetapan Badan Usaha Pemrakarsa',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Penetapan PT. Tiara Cipta Nirwana sebagai Badan Usaha Pemrakarsa KPBU (Unsolicited) proyek penyediaan air minum melalui desalinasi air laut di Lombok Utara. Berdasarkan evaluasi Letter of Intent dan Studi Kelayakan teknologi Reverse Osmosis. PJPK menawarkan dua bentuk kompensasi: tambahan nilai 10% atau right to match. Ditandatangani Raden Waliadin, SE.'},
  {id:'b23',tanggal:'14 Desember 2017',nomor_surat:'03/PJPK/XII/2017',perihal:'Permohonan Personil Panitia KPBU',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan bantuan personil untuk Panitia Pengadaan Badan Usaha dalam pelaksanaan proyek KPBU SWRO di Gili Air, Gili Meno, dan Gili Trawangan. Ditujukan kepada ULP Barang/Jasa Pemerintah Kabupaten Lombok Utara. Ditandatangani Raden Waliadin, SE selaku PJPK.'},
  {id:'b24',tanggal:'14 Desember 2017',nomor_surat:'349/TIARA/XII/2017',perihal:'Persetujuan Bentuk Kompensasi',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana menyampaikan persetujuan bentuk kompensasi dalam proyek KPBU Sea Water Desalination. Merujuk penetapan No. 02/PJPK/XII/2017. Bentuk kompensasi yang dipilih: hak menyamai penawaran terbaik (right to match). Ditandatangani Direktur Made Gde Putra Yasa, ST di Badung.'},
  {id:'b25',tanggal:'15 Desember 2017',nomor_surat:'005/115/APP/2017',perihal:'Pembentukan Panitia Pemilihan Badan Usaha KPBU',pengirim:'Sekretariat Daerah Kabupaten Lombok Utara',ringkasan:'Tindak lanjut atas permohonan personil PDAM. Lima personil terpilih dari Dinas Kesehatan, Satpol PP, Kantor Camat Gangga, Kantor Panwaslu, dan Bagian APP Setda. Panitia dipimpin Gunardi, S.Sos, SKM (Ketua) dan Lalu Sahrip Arifin, SH (Sekretaris).'},
  // ── BARU dari PDF no.6: dokumen proses lelang/kualifikasi Des 2017 ──
  {id:'b26new',tanggal:'18 Desember 2017',nomor_surat:'004/DOK.L/PQ/KPBU-PDAM/XII/2017',perihal:'Pengadaan Badan Usaha Penyedia Air Bersih SWRO',pengirim:'Panitia Lelang KPBU PDAM Kabupaten Lombok Utara',ringkasan:'Dokumen Kualifikasi nomor 004/DOK.L/PQ/KPBU-PDAM/XII/2017 untuk pengadaan Badan Usaha Penyedia Air Bersih Teknologi SWRO tahun anggaran 2017. Metode pelelangan umum dengan prakualifikasi. PT. Tiara Cipta Nirwana ditetapkan sebagai pemenang kualifikasi berdasarkan pengumuman resmi No. 008/Pan.L/KPBU-PDAM/XII/2017 pada 27 Desember 2017. Rangkaian kegiatan: rapat pemberian penjelasan 20 Desember 2017, pembuktian data isian kualifikasi 22 Desember 2017. Dokumen disusun sesuai standar LKPP dan Perpres No. 54 Tahun 2010.'},
  {id:'b27new',tanggal:'18 Desember 2017',nomor_surat:'003/Pan.L/KPBU-PDAM/XII/2017',perihal:'Pengumuman Prakualifikasi',pengirim:'Panitia Lelang KPBU PDAM Kabupaten Lombok Utara',ringkasan:'Panitia Lelang KPBU PDAM Kabupaten Lombok Utara mengumumkan pelaksanaan prakualifikasi untuk pengadaan Badan Usaha Penyedia Air Bersih dengan Teknologi SWRO. Paket pekerjaan mencakup penyediaan infrastruktur air bersih di Kabupaten Lombok Utara melalui prakarsa badan usaha. Masa pendaftaran dan pengambilan dokumen kualifikasi 18–21 Desember 2017 di Kantor PDAM Kabupaten Lombok Utara. Calon peserta dapat mewakilkan pendaftaran dengan surat tugas asli dan identitas resmi.'},
  {id:'b28new',tanggal:'20 Desember 2017',nomor_surat:'-',perihal:'Berita Acara Daftar Hadir Anwijzing KPBU',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Daftar hadir kegiatan Anwijzing KPBU PDAM Kabupaten Lombok Utara tahun 2017. Rapat dilaksanakan Rabu, 20 Desember 2017 di Ruang Rapat PDAM Kab. Lombok Utara. Tercatat 12 peserta hadir, terdiri dari Direktur, Tim Investasi, Panitia Lelang, perwakilan badan usaha, dan staf PDAM. Disahkan oleh Raden Waliadin, SE selaku Direktur PDAM Kabupaten Lombok Utara.'},
  {id:'b29new',tanggal:'20 Desember 2017',nomor_surat:'02/PANITIA KPBU/2017',perihal:'Berita Acara Pemberian Penjelasan (Aanwijzing)',pengirim:'Panitia Lelang KPBU Perusahaan Daerah Air Minum Kabupaten Lombok Utara',ringkasan:'Berita Acara Pemberian Penjelasan (Aanwijzing) terkait pengadaan badan usaha penyedia air bersih teknologi SWRO melalui prakarsa badan usaha di Kabupaten Lombok Utara. Rapat dilaksanakan Rabu, 20 Desember 2017 pukul 09.00–10.30 WITA di Ruang Pertemuan Kantor PDAM. Peserta: Panitia Lelang, unsur PDAM, Tim Investasi, dan PT. Tiara Cipta Nirwana. PT. Tiara menyatakan penjelasan lingkup pekerjaan dan persyaratan kualifikasi sudah dipahami. Ditandatangani lima anggota panitia dipimpin Gunardi, SKM.'},
  {id:'b30new',tanggal:'22 Desember 2017',nomor_surat:'-',perihal:'Tanda Terima Dokumen Kualifikasi',pengirim:'Panitia Lelang KPBU PDAM Kabupaten Lombok Utara',ringkasan:'Tanda terima dokumen kualifikasi untuk paket pekerjaan pengadaan badan usaha penyedia air bersih sistem SWRO (prakarsa badan usaha). Diterbitkan oleh Panitia Lelang KPBU PDAM Kabupaten Lombok Utara, 22 Desember 2017. Calon penyedia yang menyerahkan dokumen: PT. Tiara Cipta Nirwana. Ditandatangani oleh Ketua Panitia Pengadaan Gunardi, S.Km. sebagai bukti formal penerimaan berkas kualifikasi.'},
  {id:'b31new',tanggal:'22 Desember 2017',nomor_surat:'/Pan.L/KPBU-PDAM/XII/2017',perihal:'Berita Acara Pembukaan Dokumen Kualifikasi',pengirim:'Panitia Lelang KPBU Perusahaan Daerah Air Minum Kabupaten Lombok Utara',ringkasan:'Berita Acara Pembukaan Dokumen Kualifikasi untuk proyek pengadaan badan usaha penyedia air bersih sistem SWRO di Kabupaten Lombok Utara, 22 Desember 2017. Berdasarkan Keputusan Direktur PDAM No. 800.31 Tahun 2017, PT. Tiara Cipta Nirwana sebagai pihak rekanan. Dokumen yang diperiksa mencakup aspek legalitas: SIUP, TDP, SBU, kualifikasi tenaga ahli air minum dan konstruksi. Seluruh lima anggota panitia dan perwakilan rekanan menandatangani berita acara.'},
  {id:'b32new',tanggal:'22 Desember 2017',nomor_surat:'/Pan.L/KPBU-PDAM/XII/2017',perihal:'Berita Acara Evaluasi Kualifikasi',pengirim:'Panitia Lelang KPBU Perusahaan Daerah Air Minum Kabupaten Lombok Utara',ringkasan:'Berita Acara Evaluasi Kualifikasi, 22 Desember 2017, untuk proyek pengadaan badan usaha penyedia air bersih SWRO. Evaluasi dilakukan terhadap PT. Tiara Cipta Nirwana berdasarkan 20 kriteria kualifikasi mencakup aspek administrasi, teknis, dan sertifikasi. Kriteria meliputi legalitas perusahaan (SIUP, TDP, IUJK), kualifikasi tenaga ahli (SKA dan SKK), serta kepatuhan terhadap ISO 9001:2015 dan OHSAS 18001:2007. Ditandatangani lima anggota Panitia Pengadaan di Tanjung, Kabupaten Lombok Utara.'},
  {id:'b33new',tanggal:'22 Desember 2017',nomor_surat:'/Pan.L/KPBU-PDAM/XII/2017',perihal:'Undangan Pembuktian Kualifikasi',pengirim:'Panitia Lelang KPBU Perusahaan Daerah Air Minum Kabupaten Lombok Utara',ringkasan:'Undangan kepada Direktur PT. Tiara Cipta Nirwana untuk menghadiri agenda Pembuktian Dokumen Kualifikasi. Kegiatan dijadwalkan Rabu, 27 Desember 2017 pukul 08.00 WIB di Sekretariat PDAM Kabupaten Lombok Utara. Peserta diwajibkan membawa dokumen asli sesuai data kualifikasi yang diunggah di aplikasi SPSE. Kehadiran wajib bagi Direktur atau penerima kuasa; kelalaian mengakibatkan gugur dalam proses lelang.'},
  {id:'b34new',tanggal:'27 Desember 2017',nomor_surat:'/Pan.L/KPBU-PDAM/XII/2017',perihal:'Berita Acara Pembuktian Kualifikasi',pengirim:'Panitia Lelang KPBU PDAM Kabupaten Lombok Utara',ringkasan:'Berita Acara pembuktian data isian kualifikasi untuk proyek pengadaan badan usaha penyedia air bersih SWRO di PDAM Kabupaten Lombok Utara, Rabu 27 Desember 2017. Berdasarkan SK Direktur PDAM No. 800.31 Tahun 2017. Evaluasi mencakup verifikasi dokumen asli: SIUP, TDP, IUJK, SBU, NPWP, SPT, kualifikasi tenaga ahli (SKA/SKK), pengalaman kerja, serta sertifikasi ISO 9001:2015 dan OHSAS 18001:2007. Ditandatangani lima anggota Panitia Pengadaan.'},
  {id:'b35new',tanggal:'27 Desember 2017',nomor_surat:'008/Pan.L/KPBU-PDAM/XII/2017',perihal:'Pengumuman Pemenang Kualifikasi',pengirim:'Panitia Lelang KPBU Perusahaan Daerah Air Minum Kab. Lombok Utara',ringkasan:'Panitia Lelang KPBU PDAM Kabupaten Lombok Utara mengumumkan hasil kualifikasi pengadaan badan usaha penyedia air bersih teknologi SWRO tahun 2017. Berdasarkan surat penetapan No. 007/Pan.L/KPBU-PDAM/XII/2017, PT. Tiara Cipta Nirwana dinyatakan lulus kualifikasi. Beralamat di Jalan LC. Gatot Subroto Barat No. 3 Kerobokan Kaja Denpasar Bali, NPWP 01.112.457.5-904.000. Ditandatangani Gunardi, S.Km selaku Ketua Panitia.'},
  {id:'b26',tanggal:'22 Desember 2017',nomor_surat:'-',perihal:'Pengisian Dokumen Kualifikasi',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Isian Kualifikasi PT. Tiara Cipta Nirwana untuk pengadaan badan usaha air bersih teknologi SWRO di PDAM Kabupaten Lombok Utara tahun anggaran 2017. Mencakup Pakta Integritas, data administrasi, izin usaha SIUP dan SIUJK, dan sertifikasi ISO. Terdapat daftar pengalaman kerja 10 tahun, salah satunya proyek senilai Rp 13.152.364.500. Ditandatangani Direktur I Made Gde Putra Yasa.'},
  // ── 2018 ──
  {id:'c1',tanggal:'01 Februari 2018',nomor_surat:'05/PJPK/II/2018',perihal:'Permintaan Volume Air SWRO Gili Trawangan',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Pengajuan permintaan volume air Sea Water Reverse Osmosis (SWRO) dari PDAM Kabupaten Lombok Utara kepada PT. Tiara Cipta Nirwana. Berdasarkan kontrak KPBU Penyediaan Air Bersih, PDAM meminta pasokan sebesar 6000 m3 per hari untuk wilayah Gili Trawangan. Ditandatangani Raden Waliadin, SE selaku PJPK.'},
  {id:'c2',tanggal:'13 Februari 2018',nomor_surat:'01/TK-KI KLU/02/2018',perihal:'Laporan Hasil Kunjungan Pabrik Desalinasi',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Laporan hasil kunjungan lapangan ke pabrik desalinasi PT TIARA CIPTA NIRWANA di Bali pada 17-19 Januari 2018. Tim melakukan pengecekan peralatan mesin dan uji coba konsumsi air minum hasil pengolahan air laut. Rekomendasi: PT TIARA segera ajukan penawaran harga air minum untuk wilayah Lombok Utara daratan dan membentuk tim bersama identifikasi kebutuhan air pelanggan bisnis (hotel). Ditandatangani di Mataram 13 Februari 2018.'},
  {id:'c3',tanggal:'19 Februari 2018',nomor_surat:'539.14/PDAM-KLU/II/2018',perihal:'Permohonan Pendampingan TP4D',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan pendampingan dari PDAM kepada Tim Pengawal Pengamanan Pemerintah dan Pembangunan Daerah (TP4D) Kejaksaan Negeri Mataram. Diajukan sehubungan dengan akan dimulainya pembangunan fisik Plant SWRO di Kabupaten Lombok Utara bersama PT. Tiara Cipta Nirwana. Tujuan: memastikan proyek berjalan tepat waktu sesuai kontrak dan mematuhi peraturan yang berlaku. Ditandatangani Raden Waliadin, SE.'},
  {id:'c4',tanggal:'21 Februari 2018',nomor_surat:'B-03/TP4D.Mataram/Set/02/2018',perihal:'Persetujuan Pendampingan Kejaksaan',pengirim:'Kejaksaan Negeri Mataram',ringkasan:'Kejaksaan Negeri Mataram menyatakan kesediaan untuk melakukan pengawalan dan pengamanan terhadap pembangunan fisik Plant SWRO di Kabupaten Lombok Utara. Merupakan tanggapan atas permohonan PDAM No. 539.14/PDAM-KLU/II/2018 tertanggal 19 Februari 2018. Tim TP4D meminta pemaparan teknis proyek di Kantor Kejaksaan Negeri Mataram menghadirkan Konsultan Perencana, PPK, Kontraktor Pelaksana, dan Konsultan Pengawas.'},
  {id:'c5',tanggal:'05 Januari 2018',nomor_surat:'01/PJPK/I/2018',perihal:'Penetapan Pemenang Kualifikasi',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Penetapan PT. Tiara Cipta Nirwana sebagai pemenang badan usaha penyedia air bersih teknologi SWRO di Lombok Utara. Berdasarkan Pengumuman Pemenang Kualifikasi No. 008/Pan.L/KPBU-PDAM/XII/2017 tanggal 27 Desember 2017. Berkas dokumen kualifikasi diterima dan disetujui sepenuhnya. Tembusan kepada Bupati dan Inspektur Kabupaten Lombok Utara.'},
  {id:'c6',tanggal:'05 Januari 2018',nomor_surat:'005/TIARA/I/2018',perihal:'Penawaran Harga Air Bersih',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Penawaran harga air bersih hasil olahan SWRO. Harga untuk wilayah Gili Matra: Rp 34.000,- per meter kubik. Harga untuk daratan Pulau Lombok: Rp 32.000,- per meter kubik. Ditandatangani Direktur I Made Gde Putra Yasa, 5 Januari 2018.'},
  {id:'c7',tanggal:'08 Januari 2018',nomor_surat:'539.03/PDAM-KLU/I/2018',perihal:'Permohonan Review Harga Air Bersih',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan kepada Tim Pengkaji Kerjasama Investasi untuk meninjau kelayakan harga air bersih hasil olahan SWRO. Diajukan menyusul surat penawaran harga PT Tiara Cipta Nirwana. Ditandatangani Direktur PDAM Raden Waliadin.'},
  {id:'c8',tanggal:'09 Januari 2018',nomor_surat:'005/03/KLU/2018',perihal:'Undangan Penandatanganan Kontrak KPBU',pengirim:'Bupati Lombok Utara',ringkasan:'Bupati Lombok Utara mengundang Dirjen Bina Konstruksi Kementerian PUPR RI untuk penandatanganan kontrak proyek KPBU bidang air minum. Dijadwalkan Selasa, 16 Januari 2018 pukul 08.00 WITA di Aula Kantor Bupati Lombok Utara. Ditandatangani Dr. H. Najmul Akhyar selaku Bupati.'},
  {id:'c9',tanggal:'10 Januari 2018',nomor_surat:'04/TK-KI KLU/01/2018',perihal:'Hasil Review Penawaran Harga Air',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Hasil evaluasi Tim Pengkaji terhadap tawaran harga air PT Tiara Cipta Nirwana. Penawaran awal: Rp 34.000/m3 (Gili Matra) dan Rp 32.000/m3 (daratan Lombok Utara). Tim menyusun skenario harga beli Rp 30.000/m3 dengan asumsi investasi jaringan maksimal Rp 10 miliar dan bunga tahunan 13%. Analisis NPV menunjukkan proyek tidak layak jika tingkat bunga 16%.'},
  {id:'c10',tanggal:'26 Maret 2018',nomor_surat:'06/PJPK/III/2018',perihal:'Permintaan Volume SWRO Gili Meno',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara kepada PT Tiara Cipta Nirwana mengajukan permintaan volume air berdasarkan Kontrak KPBU menggunakan teknologi Reverse Osmosis. Lokasi: wilayah Gili Meno dengan kebutuhan sebesar 2000 M3 per hari. Ditandatangani Raden Waliadin, SE selaku PJPK.'},
  {id:'c11',tanggal:'02 April 2018',nomor_surat:'07/PJPK/IV/2018',perihal:'Permintaan Penawaran Harga Wilayah Daratan',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara meminta penawaran harga penyediaan air bersih untuk wilayah daratan di Kabupaten Lombok Utara yang saat ini belum terjangkau layanan mereka. Berdasarkan Kontrak KPBU penyediaan air bersih layak minum teknologi Reverse Osmosis. Ditandatangani Raden Waliadin, SE selaku PJPK.'},
  {id:'c12',tanggal:'23 April 2018',nomor_surat:'08/PJPK/IV/2018',perihal:'Pemberitahuan Permintaan Laporan Progres',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PJPK PDAM Kabupaten Lombok Utara meminta laporan progres perkembangan pelaksanaan proyek penyediaan air bersih layak minum melalui teknologi Reverse Osmosis dari PT. Tiara Cipta Nirwana. Berdasarkan Kontrak KPBU. Ditandatangani Raden Waliadin, SE selaku PJPK.'},
  {id:'c13',tanggal:'25 April 2018',nomor_surat:'B-05/TP4D.MTR/SET/04/2018',perihal:'Jawaban Permohonan Pendampingan TP4D',pengirim:'Kejaksaan Negeri Mataram',ringkasan:'Jawaban resmi Kejaksaan Negeri Mataram atas permohonan pendampingan TP4D dari Direktur PDAM Lombok Utara. Merujuk permohonan No. 539.14/PDAM-KLU/II/2018 tanggal 19 Februari 2018. Pihak Kejaksaan menyatakan kesediaan melakukan pengawalan dan pengamanan terhadap kegiatan pembangunan SWRO. Ditandatangani Agus Taufikurrahman selaku Ketua TP4D Kejari Mataram.'},
  {id:'c14',tanggal:'08 Mei 2018',nomor_surat:'128.2/TIARA/V/2018',perihal:'Penawaran Harga Air Bersih Daratan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT Tiara Cipta Nirwana mengajukan penawaran harga air bersih layak minum melalui teknologi Reverse Osmosis sebesar Rp 34.000,- per meter kubik untuk wilayah daratan yang belum terjangkau layanan PDAM. Tindak lanjut atas surat permintaan PJPK PDAM tertanggal 2 April 2018. Dilampirkan tanda terima surat tanggal 8 Mei 2018.'},
  {id:'c15',tanggal:'04 Juni 2018',nomor_surat:'09/PJPK/VI/2018',perihal:'Permintaan Rincian Penawaran Tarif',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara meminta rincian perhitungan tarif yang ditawarkan PT. Tiara Cipta Nirwana. Tindak lanjut atas surat No. 128.2/TIARA/V/2018 mengenai hasil olahan SWRO di Kabupaten Lombok Utara. Ditandatangani Raden Waliadin, SE selaku PJPK.'},
  {id:'c16',tanggal:'07 Juni 2018',nomor_surat:'158/TIARA/VI/2018',perihal:'Rincian Tarif Air Bersih',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Rincian perhitungan tarif air bersih hasil olahan SWRO untuk wilayah darat. CAPEX total: Rp 21.950.607.750 dan biaya operasional tahunan: Rp 4.878.217.691 untuk kapasitas 1.000 m3 per hari. Berdasarkan parameter investasi jangka waktu 10 tahun dan bunga 12,5%, harga pokok produksi ditetapkan Rp 34.087 per m3. Mencakup detail teknis dari pembuatan sumur hingga komponen operasional listrik dan tenaga kerja.'},
  {id:'c17',tanggal:'21 Juni 2018',nomor_surat:'11/PJPK/VI/2018',perihal:'Permohonan Rekomendasi Penggalian Pipa',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara mengajukan permohonan rekomendasi kepada Kepala Desa Gili Indah terkait rencana penggalian pipa distribusi air bersih siap minum di Gili Trawangan. Bagian dari Rencana Strategis PDAM 2018-2022 untuk mempercepat dan memperluas cakupan layanan air bersih. Pembangunan infrastruktur pipa distribusi direncanakan pada tahun anggaran 2018.'},
  {id:'c18',tanggal:'21 Juni 2018',nomor_surat:'10/PJPK/VI/2018',perihal:'Permohonan Rekomendasi Pengambilan Air Baku',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan rekomendasi pengambilan air baku kepada Kepala Desa Gili Indah. Terkait Rencana Strategis PDAM 2018-2022 untuk perluasan cakupan pelayanan air bersih. Proyek SPAM Gili Trawangan melalui skema KPBU teknologi Reverse Osmosis dengan pengambilan air baku melalui pengeboran Beach Well di wilayah Gili Indah.'},
  {id:'c19',tanggal:'22 Juni 2018',nomor_surat:'503/91b/Pemb./03/VI/2018',perihal:'Rekomendasi Izin Pengelolaan Air',pengirim:'Kepala Desa Gili Indah',ringkasan:'Rekomendasi Ijin dari Pemerintah Desa Gili Indah kepada PDAM Kabupaten Lombok Utara. Diberikan untuk pengelolaan air bersih menggunakan teknologi Reverse Osmosis, mencakup pengambilan air laut (desalinasi) serta penggalian pipa distribusi. Lokasi: Dusun Gili Trawangan dan Gili Meno, Desa Gili Indah, Kecamatan Pemenang. Berdasarkan hasil pengecekan lapangan dan kelengkapan administrasi.'},
  {id:'c20',tanggal:'25 Juni 2018',nomor_surat:'12/PJPK/VI/2018',perihal:'Permohonan Review Kelayakan Harga SWRO',pengirim:'PJPK PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan kepada Tim Pengkaji Kerjasama Investasi untuk meninjau harga air bersih hasil olahan SWRO. Menindaklanjuti surat penawaran PT Tiara Cipta Nirwana No. 158/TIARA/VI/2018 tanggal 7 Juni 2018. Fokus: evaluasi kelayakan harga penawaran badan usaha pemrakarsa terkait proyek SPAM daratan Kabupaten Lombok Utara. Ditandatangani Raden Waliadin, SE.'},
  // ── BARU dari PDF no.6: permohonan addendum kontrak 30 Juni 2018 ──
  {id:'c20new',tanggal:'30 Juni 2018',nomor_surat:'184/TIARA/VI/2018',perihal:'Permohonan Addendum Kontrak',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana mengajukan permohonan addendum kontrak kerjasama penyediaan air bersih berbasis teknologi Reverse Osmosis kepada PDAM Kabupaten Lombok Utara. Permohonan dipicu oleh kendala penetapan titik sumur pengambilan air baku di wilayah konservasi Gili Trawangan yang memerlukan koordinasi izin lokasi tambahan. Perusahaan membutuhkan waktu lebih untuk berkoordinasi dengan instansi pemerintah mengenai pemanfaatan ruang laut. Usulan addendum didasarkan pada Pasal 16 kontrak asli. Ditandatangani Direktur I Made Gde Putra Yasa, 30 Juni 2018.'},
  {id:'c21',tanggal:'02 Juli 2018',nomor_surat:'01441',perihal:'Permohonan Addendum Kontrak',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Tanda terima dan draf addendum perjanjian kerjasama penyediaan air bersih antara PDAM Lombok Utara dan PT. Tiara Cipta Nirwana. Mencakup perubahan pada Pasal 5 (tata cara konstruksi) dan Pasal 11 (jaminan para pihak). Kewajiban Badan Usaha: menyelesaikan instalasi mesin RO dalam jangka waktu maksimal 12 bulan sejak desain disetujui. Melibatkan Direktur PDAM Raden Waliadin sebagai Pihak Pertama dan Direktur PT. Tiara I Made Gde Putra Yasa sebagai Pihak Kedua.'},
  {id:'c22',tanggal:'13 Juli 2018',nomor_surat:'13/PJPK/VII/2018',perihal:'Permohonan Koordinasi dan Rekomendasi KKP',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara mengajukan permohonan koordinasi dan rekomendasi kepada Menteri Kelautan dan Perikanan terkait pembangunan SPAM Gili Trawangan. Bagian dari Rencana Strategis PDAM 2018-2022. Proyek menggunakan skema KPBU dengan teknologi desalinasi Reverse Osmosis. Pengambilan air baku direncanakan melalui pengeboran sumur pantai di wilayah Gili Trawangan dan Gili Meno.'},
  // ── BARU dari PDF no.6: permohonan Kepala Desa Gili Indah 18 Juli 2018 ──
  {id:'c22new',tanggal:'18 Juli 2018',nomor_surat:'501/143/03/VII/2018',perihal:'Permohonan Peningkatan Pelayanan Air Gili Air',pengirim:'Kepala Desa Gili Indah',ringkasan:'Surat dari Pemerintah Desa Gili Indah kepada Direktur PDAM Kabupaten Lombok Utara memohon peningkatan pelayanan air di Dusun Gili Air yang saat ini dinilai sangat kurang maksimal. Dokumen menyertakan lampiran daftar nama dan tanda tangan warga beserta alamat dan nomor telepon sebagai bentuk dukungan permohonan. Ditandatangani Kepala Desa Gili Indah, H.M. Taufik, 18 Juli 2018.'},
  {id:'c23',tanggal:'27 Juli 2018',nomor_surat:'02/TK-KI KLU/07/2018',perihal:'Laporan Review Kelayakan Harga SWRO',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Hasil review kelayakan harga air bersih hasil olahan SWRO oleh PT Tiara Cipta Nirwana. Tim menemukan perusahaan belum mengajukan harga penawaran jual resmi, baru menyertakan rincian biaya investasi darat. CAPEX darat: Rp21.950.607.750, biaya operasional tahunan Rp4.878.217.691, kapasitas 1.000 m3/hari. Rekomendasi: ajukan surat penawaran harga jual baru dan revisi perhitungan harga pokok produksi berdasarkan kapasitas terpasang 100%.'},
  {id:'c24',tanggal:'27 Juli 2018',nomor_surat:'14/PJPK/VII/2018',perihal:'Permohonan Review Addendum Kontrak',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan kepada Tim Pengkaji Kerjasama Investasi untuk mereview usulan addendum kontrak KPBU dari PT Tiara Cipta Nirwana No. 1814/TIARA/VI/2018. Merupakan pengantar administratif untuk memulai proses kajian teknis dan hukum terhadap kontrak. Ditandatangani Raden Waliadin, SE, 27 Juli 2018 di Tanjung.'},
  {id:'c25',tanggal:'30 Juli 2018',nomor_surat:'03/TK-KI KLU/07/2018',perihal:'Laporan Review Addendum Kontrak',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Hasil review Tim Pengkaji terhadap permohonan addendum kontrak KPBU. Perubahan krusial: perpanjangan jangka waktu konstruksi mesin RO menjadi maksimal 18 bulan sejak izin pengolahan air baku diterbitkan. Disepakati hak istimewa investasi di mana pihak pertama dilarang memberikan izin usaha serupa kepada pihak lain di lokasi proyek. Addendum akan dilaksanakan setelah verifikasi laporan kemajuan fisik.'},
  {id:'c26',tanggal:'15 Oktober 2018',nomor_surat:'15/PJPK/X/2018',perihal:'Permohonan Petunjuk TP4D Addendum',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'PDAM Kabupaten Lombok Utara mengajukan permohonan petunjuk kepada TP4D Kejaksaan Negeri Mataram terkait rencana addendum kontrak. Diajukan menyusul permohonan addendum Kontrak KPBU No. 1814/TIARA/VI/2018 dari PT Tiara Cipta Nirwana. PDAM membutuhkan pertimbangan atau arahan hukum dari TP4D. Ditandatangani Raden Waliadin, SE, 15 Oktober 2018.'},
  {id:'c27',tanggal:'22 Oktober 2018',nomor_surat:'16/PJPK/XI/2018',perihal:'Permohonan Perpanjangan Pendampingan TP4D',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan perpanjangan pendampingan TP4D kepada Kejaksaan Negeri Mataram karena pembangunan fisik instalasi SWRO belum selesai sesuai target. Perpanjangan diharapkan menjaga proyek berjalan sesuai jangka waktu kontrak dengan PT. Tiara Cipta Nirwana. Tujuan: memastikan seluruh tahapan pembangunan mematuhi peraturan hukum yang berlaku. Ditandatangani Raden Waliadin, SE.'},
  {id:'c28',tanggal:'29 Oktober 2018',nomor_surat:'302/TIARA/X/2018',perihal:'Penawaran Harga Air Bersih Daratan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana mengirimkan surat penawaran harga air bersih kepada PJPK KPBU di Kabupaten Lombok Utara. Merujuk pada hasil review kelayakan harga Tim Pengkaji No. 02/TK-KIKLU/07/2018. Harga yang ditawarkan untuk air bersih hasil olahan SWRO daratan: Rp 32.000,- per meter kubik. Dilampirkan dasar perhitungan harga pokok produksi dan harga jual.'},
  // ── BARU dari PDF no.6: Addendum Pertama 12 November 2018 ──
  {id:'c28new',tanggal:'12 November 2018',nomor_surat:'17/PJPK/XI/2018',perihal:'Addendum Pertama Perjanjian Kerjasama',pengirim:'PDAM Kabupaten Lombok Utara dan PT Tiara Cipta Nirwana',ringkasan:'Addendum Pertama atas perjanjian kerjasama penyediaan air bersih menggunakan teknologi Reverse Osmosis antara PDAM Kabupaten Lombok Utara dan PT Tiara Cipta Nirwana. Perubahan dilakukan akibat keterlambatan penerbitan izin operasional yang berdampak pada jadwal konstruksi dan instalasi mesin. Jangka waktu penyelesaian konstruksi disepakati menjadi maksimal 18 bulan untuk periode 6 Desember 2018 hingga 6 Desember 2019. Ditandatangani di Tanjung 12 November 2018 dengan persetujuan Bupati Lombok Utara. Addendum menegaskan kepastian investasi melalui hak previlese serta rencana penerbitan rekening bersama.'},
  // ── 2019 ──
  {id:'d1',tanggal:'07 Januari 2019',nomor_surat:'01/PJPK/I/2019',perihal:'Permohonan Rekomendasi Pengambilan Air Laut',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan koordinasi dan rekomendasi pengambilan air laut kepada DPMPTSP Provinsi NTB untuk wilayah Gili Matra. Sesuai Rencana Strategis PDAM 2018-2022. Teknologi Reverse Osmosis mengolah air laut menjadi air siap minum. Metode yang diusulkan: pengeboran miring (Slant Beach Well) di pesisir pantai Gili Trawangan dan Gili Meno.'},
  {id:'d2',tanggal:'10 Januari 2019',nomor_surat:'005/03.05.3/DPMPTSP/2019',perihal:'Undangan Presentasi Rencana Kegiatan Usaha',pengirim:'Dinas Penanaman Modal dan PTSP Provinsi NTB',ringkasan:'Undangan dari DPMPTSP Provinsi NTB kepada Direktur PDAM Kabupaten Lombok Utara untuk mempresentasikan rencana kegiatan usaha. Menindaklanjuti proposal pembangunan sarana pengambilan air laut di Gili Matra tanggal 7 Januari 2019. Presentasi dijadwalkan Rabu, 16 Januari 2019, pukul 09.00 WITA di Ruang Rapat DPMPTSP NTB. Ditandatangani Kepala Dinas Drs. H. Lalu Gita Ariadi, M.Si.'},
  {id:'d3',tanggal:'17 Januari 2019',nomor_surat:'02/PJPK/I/2019',perihal:'Permohonan Pengkajian Metode Pengambilan Air Laut',pengirim:'Direktur PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan pengkajian terkait rencana pembangunan sarana pengambilan air laut di Kawasan Gili Matra. Lampiran: kajian pemilihan metode SWRO melalui skema KPBU. Tim pengkaji mengusulkan metode submarine saline water intake dengan spesifikasi teknis pemboran miring sedalam 110 meter untuk Gili Trawangan. Menyoroti perlunya diskresi hukum karena keterbatasan regulasi pemanfaatan air laut.'},
  {id:'d4',tanggal:'21 Januari 2019',nomor_surat:'01/TK-KI KLU/01/2019',perihal:'Laporan Kajian Metode Pemanfaatan Air Laut',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Hasil kajian mengenai pemilihan metode pemanfaatan air laut sebagai sumber air baku di Tiga Gili. Metode slant well (sumur miring) ke bawah dasar laut dinilai paling layak secara teknis dan lingkungan. Keunggulan: perlindungan biota laut dan pencegahan kerusakan air tanah di daratan. Lokasi proyek berada di luar wilayah Cekungan Air Tanah (CAT) sesuai Keppres RI No. 26 Tahun 2011.'},
  {id:'d5',tanggal:'21 Januari 2019',nomor_surat:'03/PJPK/I/2019',perihal:'Permohonan Pertimbangan Teknis Izin Pemanfaatan Air Laut',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan pertimbangan teknis kepada Dinas Kelautan dan Perikanan Provinsi NTB terkait izin pemanfaatan air laut sebagai sumber air baku di kawasan Tiga Gili. Mengusulkan metode slant well (sumur miring) yang lebih ramah lingkungan. Rencana: sumur di Gili Trawangan, Gili Meno, dan Gili Air dengan collar berjarak 15 meter dari bibir pantai, kemiringan 75 derajat, kedalaman 110 meter.'},
  {id:'d6',tanggal:'20 Februari 2019',nomor_surat:'176/DJPRL/II/2019',perihal:'Tanggapan Permohonan Rekomendasi Pengambilan Air Baku',pengirim:'Direktorat Jenderal Pengelolaan Ruang Laut KKP',ringkasan:'Tanggapan terkait permohonan koordinasi pengambilan air baku di Gili Trawangan oleh PDAM Lombok Utara. Rencana penggunaan SWRO melalui sumur pantai dikategorikan sebagai aktivitas pengambilan air tanah. Jika metode sumur pantai dipertahankan, izin pengusahaan air tanah harus dimohonkan kepada Gubernur. Jika instalasi diubah tanpa metode pengeboran, kementerian dapat memberikan rekomendasi pemanfaatan pulau-pulau kecil.'},
  {id:'d7',tanggal:'01 April 2019',nomor_surat:'05/PJPK/III/2019',perihal:'Permohonan Izin Lokasi Laut',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan Izin Lokasi Laut untuk pengambilan air laut sebagai air baku menggunakan metode sumur miring. Lokasi: Desa Gili Indah, Kecamatan Pamenang, total luas area 19.845 m2 atau 1,9835 Ha. Menyertakan NIB, Izin Lokasi dari OSS, dan proposal pemenuhan komitmen. Ditandatangani Direktur PDAM Raden Waliadin, SE.'},
  {id:'d8',tanggal:'10 April 2019',nomor_surat:'005/03.437/DPM-PTSP/2019',perihal:'Undangan Pertemuan Koordinasi Izin Lokasi Laut',pengirim:'Dinas Penanaman Modal dan PTSP Provinsi NTB',ringkasan:'Undangan resmi dari DPMPTSP Provinsi NTB untuk pertemuan koordinasi tindak lanjut permohonan Izin Lokasi Laut terkait rencana pengambilan air laut dengan pengeboran miring di Gili Indah. Dijadwalkan Jumat, 12 April 2019, pukul 09.00 WITA di Ruang Rapat DPMPTSP Provinsi NTB. Ditandatangani Drs. H. Lalu Gita Ariadi, M.Si.'},
  {id:'d9',tanggal:'12 April 2019',nomor_surat:'-',perihal:'Kesimpulan Rapat Permohonan Izin Lokasi Laut',pengirim:'DPMPTSP Provinsi NTB',ringkasan:'Kesimpulan rapat 12 April 2019. Rapat menyepakati bahwa pemanfaatan air baku melalui sistem pengeboran miring SWRO termasuk kategori pengambilan air tanah sesuai tanggapan KKP No. 176/DJPR/II/2019. Kegiatan pengeboran di Gili Trawangan tidak diperbolehkan karena kondisi struktur tanah. Disepakati usulan permintaan legal opinion yang diinisiasi oleh DPMPTSP Provinsi NTB.'},
  {id:'d10',tanggal:'25 April 2019',nomor_surat:'06/PJPK/IV/2019',perihal:'Permohonan Izin Lokasi dan Pengelolaan Sumberdaya Perairan',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan Izin Lokasi dan Izin Pengelolaan Sumberdaya Perairan Pesisir kepada Kepala DPMPTSP Provinsi NTB. Area 19.845 m2 di Desa Gili Indah untuk pengambilan air laut sebagai bahan baku air bersih. Menyertakan NIB, izin lokasi dari OSS, dan surat tanggapan KKP. Ditandatangani Raden Waliadin, SE.'},
  {id:'d11',tanggal:'25 April 2019',nomor_surat:'07/PJPK/IV/2019',perihal:'Permohonan Rekomendasi Pemanfaatan Pulau Kecil',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan rekomendasi pemanfaatan pulau-pulau kecil dan izin lokasi perairan pesisir seluas 19.845 m2 di Desa Gili Indah kepada Kementerian Kelautan dan Perikanan RI. Rencana penggunaan untuk pengambilan air laut sebagai air baku penyediaan air bersih siap minum. Ditandatangani Raden Waliadin, SE.'},
  {id:'d12',tanggal:'03 Mei 2019',nomor_surat:'08/PJPK/V/2019',perihal:'Permohonan Izin Lokasi Perairan Pesisir',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan izin lokasi perairan pesisir kepada DPMPTSP Provinsi NTB untuk rencana pengambilan air laut sebagai sumber air baku di Desa Gili Indah, Kecamatan Pemenang. Luas area 19.845 m2 atau 1,9835 hektar. Melampirkan peta lokasi dengan koordinat geografis dan data hasil survei kondisi ekosistem pesisir. Ditandatangani Raden Waliadin, SE.'},
  {id:'d13',tanggal:'16 Mei 2019',nomor_surat:'09/PJPK/V/2019',perihal:'Permohonan Izin Lokasi Perairan Pesisir (Lanjutan)',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan izin lokasi perairan pesisir untuk rencana pengambilan air laut sebagai air baku di Desa Gili Indah, Kecamatan Pemenang, luas area 19.845 m2 atau 1,9835 hektar. Diterbitkan 16 Mei 2019, ditandatangani Raden Waliadin, SE. Melampirkan peta lokasi skala 1:5000 dan data survei kondisi ekosistem pesisir.'},
  {id:'d14',tanggal:'16 Juli 2019',nomor_surat:'043/55/TKPRD-KLU/2019',perihal:'Rekomendasi Kesesuaian Pemanfaatan Ruang',pengirim:'Tim Koordinasi Penataan Ruang Daerah (TKPRD) Kabupaten Lombok Utara',ringkasan:'TKPRD Kabupaten Lombok Utara menerbitkan rekomendasi kesesuaian pemanfaatan ruang untuk pembangunan rumah produksi air bersih PT. Tiara Cipta Nirwana. Proyek di lahan 3115 m² di Dusun Gili Trawangan, Desa Gili Indah. Berdasarkan rapat koordinasi 16 Juli 2019 dan Perda No. 9 Tahun 2011 tentang RTRW. Mewajibkan koordinasi perizinan AMDAL, IMB, dan kepatuhan aturan zonasi.'},
  {id:'d15',tanggal:'17 Juli 2019',nomor_surat:'198/TIARA/VII/2019',perihal:'Permohonan Addendum Kontrak Kedua',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan Addendum ke-2 terkait proyek kerjasama penyediaan air bersih RO kepada PDAM Lombok Utara. Mencakup perpanjangan waktu konstruksi mesin R.O selama maksimal 12 bulan karena kendala perizinan di wilayah konservasi Gili Trawangan. Menetapkan PT Sarana Tirta Nirwana sebagai Badan Usaha Pelaksana (BUP). Addendum pertama berlaku 6 Desember 2018 hingga 6 Desember 2019.'},
  {id:'d16',tanggal:'22 Juli 2019',nomor_surat:'12/PJPK/VII/2019',perihal:'Penjelasan Proyek KPBU kepada BPKP',pengirim:'Direktur PDAM Kabupaten Lombok Utara selaku PJPK',ringkasan:'Penjelasan resmi kepada Kepala BPKP Perwakilan Provinsi NTB terkait hasil kegiatan KORSUPGAH KPK pada 10 Juli 2019. Difokuskan pada pertanyaan tim KPK mengenai Proyek KPBU SPAM dengan mitra PT Tiara Cipta Nirwana. Materi jawaban telah dikonsultasikan dengan Tim Pengkaji Kerjasama Investasi PDAM Lombok Utara. Ditandatangani Raden Waliadin, SE.'},
  {id:'d17',tanggal:'22 Juli 2019',nomor_surat:'07/TK-KI KLU/VII/2019',perihal:'Tanggapan Pertanyaan Tim Korsupgah KPK',pengirim:'Tim Pengkaji Kerjasama Investasi PDAM KLU',ringkasan:'Tanggapan resmi terhadap pertanyaan Tim Korsupgah KPK mengenai kelanjutan KPBU antara PDAM Lombok Utara dan PT. Tiara Cipta Nirwana. Merinci penyesuaian harga air dari Rp 54.375 menjadi Rp 36.000 per meter kubik berdasarkan tinjauan BPKP NTB. PDAM menerima bagi hasil Rp 2.000 per meter kubik. Menjelaskan kewenangan pemerintah kabupaten menutup sumur air bawah tanah dan skema Build Own Operate (BOO).'},
  {id:'d18',tanggal:'05 Agustus 2019',nomor_surat:'005/37-TKPRD/2019',perihal:'Undangan Rapat Koordinasi Kesesuaian Tata Ruang',pengirim:'TKPRD Provinsi NTB',ringkasan:'TKPRD Provinsi NTB mengundang berbagai pihak untuk rapat koordinasi 6 Agustus 2019 membahas permohonan rekomendasi kesesuaian tata ruang untuk proyek desalinasi PT Tiara Cipta Nirwana di Kabupaten Lombok Utara. Rapat bertempat di Kantor Dinas PUPR Provinsi NTB dan melibatkan kepala bidang serta perwakilan instansi teknis terkait.'},
  {id:'d19',tanggal:'14 Agustus 2019',nomor_surat:'005/44-TKPRD/2019',perihal:'Undangan Kunjungan Lapangan Kesesuaian Tata Ruang',pengirim:'Tim Koordinasi Penataan Ruang Daerah (TKPRD) Provinsi NTB',ringkasan:'Undangan kunjungan lapangan dari TKPRD Provinsi NTB sebagai tindak lanjut rapat pembahasan rekomendasi kesesuaian tata ruang. Terkait rencana proyek desalinasi PT. Tiara Cipta Nirwana di Gili Trawangan. Dijadwalkan Kamis, 15 Agustus 2019, berkumpul di Dinas PUPR Provinsi NTB pukul 08.30 WITA.'},
  {id:'d20',tanggal:'15 Agustus 2019',nomor_surat:'31/BA-TKPRD/2019',perihal:'Berita Acara Survei Lapangan TKPRD',pengirim:'Tim Koordinasi Penataan Ruang Daerah (TKPRD) Provinsi NTB',ringkasan:'Berita acara hasil survei lapangan 15 Agustus 2019 terkait rencana pembangunan rumah pompa dan pengolahan air laut PT. Tiara Cipta Nirwana di Gili Trawangan. Lokasi proyek berada di Zona Perikanan Tangkap dan sesuai Perda Lombok Utara No. 9 Tahun 2011 tentang RTRW. Para pihak menyepakati pembangunan tidak boleh mengganggu alur pelayaran nelayan dan wajib menjamin akses publik ke pantai.'},
  {id:'d21',tanggal:'02 September 2019',nomor_surat:'13/PJPK/IX/2019',perihal:'Permohonan Ekspose dan Review Kelayakan Investasi',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Permohonan resmi kepada Kepala BPKP Perwakilan Provinsi NTB untuk melakukan ekspose dan review kelayakan investasi dari kerjasama KPBU antara PDAM Lombok Utara dan PT Tiara Cipta Nirwana. Diterbitkan di Tanjung, 2 September 2019. Ditandatangani Raden Waliadin selaku Direktur PDAM dan PJPK.'},
  {id:'d22',tanggal:'10 September 2019',nomor_surat:'S-2478/PW23/4/2019',perihal:'Pemberitahuan Jadwal Ekspose Kelayakan KPBU',pengirim:'BPKP Perwakilan Provinsi NTB',ringkasan:'Pemberitahuan rencana pelaksanaan ekspose atas kelayakan Investasi KPBU antara PDAM Kabupaten Lombok Utara dengan PT Tiara Cipta Nirwana. Tindak lanjut surat PDAM No. 13/PJPK/IX/2019 tanggal 2 September 2019. Ekspose dijadwalkan Senin, 16 September 2019, pukul 10.00 WITA di kantor Perwakilan BPKP Provinsi NTB.'},
  {id:'d23',tanggal:'24 Oktober 2019',nomor_surat:'14/PJPK/X/2019 dan 278/TIARA/X/2019',perihal:'Addendum Perjanjian Kerjasama Kedua',pengirim:'PDAM Kabupaten Lombok Utara dan PT. Tiara Cipta Nirwana',ringkasan:'Addendum ke-2 atas Perjanjian Kerjasama Penyediaan dan Distribusi Air Bersih Layak Minum melalui teknologi Reverse Osmosis. Disepakati karena keterlambatan penerbitan izin operasional dan pengelolaan air baku. Perpanjangan jangka waktu konstruksi mesin R.O menjadi maksimal 12 bulan, terhitung 6 Desember 2018 hingga 6 Desember 2019. Ditandatangani Direktur PDAM dan Direktur PT Tiara Cipta Nirwana dengan persetujuan Bupati Lombok Utara.'},
  {id:'d24',tanggal:'29 Oktober 2019',nomor_surat:'013/0A/DJPRL-KKP/X/2019',perihal:'Tanda Terima Permohonan Izin Lokasi Perairan (Dikembalikan)',pengirim:'PT Tiara Cipta Nirwana',ringkasan:'Tanda terima permohonan Komitmen Izin Lokasi Perairan untuk pemanfaatan air laut di Kawasan Konservasi Taman Nasional Perairan Desa Gili Indah. Dokumen dikembalikan kepada pemohon karena terdapat beberapa berkas yang harus diperbaiki: tujuan surat, konfirmasi data NIB pada sistem OSS, luasan dan koordinat lokasi, serta kelengkapan peta rencana tapak. Belum dapat diproses lebih lanjut hingga seluruh persyaratan dilengkapi.'},
  {id:'d25',tanggal:'31 Oktober 2019',nomor_surat:'014/0A/DJPRL-KKP/X/2019',perihal:'Tanda Terima Permohonan Izin Lokasi Perairan',pengirim:'Direktorat Jenderal Pengelolaan Ruang Laut KKP',ringkasan:'Tanda terima resmi atas berkas permohonan komitmen Izin Lokasi Perairan oleh PT Tiara Cipta Nirwana. Permohonan untuk pemanfaatan air laut di Kawasan Konservasi Taman Nasional Perairan Desa Gili Indah, Kabupaten Lombok Utara. Berkas meliputi NIB, proposal teknis dengan data hidro-oseanografi, dan rencana investasi usaha. Seluruh dokumen dinyatakan ada dan lengkap.'},
  {id:'d26',tanggal:'01 November 2019',nomor_surat:'S-2926/PW23/4/2019',perihal:'Penyampaian Notulen Ekspose Kelayakan',pengirim:'BPKP Perwakilan Provinsi NTB',ringkasan:'Notulen hasil ekspose kelayakan investasi KPBU antara PDAM Lombok Utara dan PT Tiara Cipta Nirwana. Tarif air ditetapkan Rp 34.000/M3 dengan kenaikan kumulatif 8% per tahun selama 30 tahun. BPKP menyoroti risiko finansial PDAM akibat klausul pembayaran minimum 80% dari volume permintaan. Terdapat denda keterlambatan 0,1% per hari dan kewajiban penutupan sumur masyarakat di Gili Matra.'},
  {id:'d27',tanggal:'13 November 2019',nomor_surat:'1234/DJPRL/XI/2019',perihal:'Tanggapan Permohonan Izin Lokasi',pengirim:'Direktorat Jenderal Pengelolaan Ruang Laut KKP',ringkasan:'Tanggapan atas permohonan PT Tiara Cipta Nirwana terkait izin lokasi perairan desalinasi di Gili Ayer, Gili Meno, dan Gili Trawangan. Ditemukan ketidaksesuaian kedalaman ujung pipa dengan data batimetri nasional. Lokasi pembuangan brine hanya 254 meter dari zona inti, berpotensi mengubah salinitas lingkungan. Perusahaan diminta mengajukan kembali permohonan setelah perbaikan teknis.'},
  {id:'d28',tanggal:'14 November 2019',nomor_surat:'310.5/TIARA/XI/2019',perihal:'Permohonan Pemenuhan Komitmen Izin Lokasi',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana mengajukan pemenuhan komitmen izin lokasi perairan di Gili Trawangan kepada KKP. Pipa pengambilan air laut direncanakan kedalaman 15-20 meter, panjang 500 meter dari garis pantai. Teknologi Reverse Osmosis (RO) digunakan untuk memproses air laut. Ditandatangani Direktur I Made Gede Putra Yasa.'},
  {id:'d29',tanggal:'14 November 2019',nomor_surat:'363/TIARA/XI/2019',perihal:'Permohonan Rekomendasi Pemanfaatan Pulau Kecil',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan rekomendasi pemanfaatan pulau-pulau kecil dari PT. Tiara Cipta Nirwana kepada Menteri KKP. Target kapasitas produksi 6.000 m3/hari, kebutuhan air baku 16.992 m3/hari di lahan 896 m2. Melampirkan delapan dokumen termasuk NIB, NPWP, peta lokasi, dan titik koordinat kegiatan.'},
  {id:'d30',tanggal:'25 November 2019',nomor_surat:'1934/DJPRL.1/XI/2019',perihal:'Permintaan Perbaikan Data Teknis',pengirim:'Direktorat Jenderal Pengelolaan Ruang Laut KKP',ringkasan:'Permintaan perbaikan data kepada PT Tiara Cipta Nirwana terkait permohonan izin lokasi perairan desalinasi. Pemohon diminta mengubah lokasi pipa pembuangan agar tidak berdekatan dengan pipa pengambilan dan Zona Inti. Perusahaan diwajibkan menggunakan teknologi Horizontal Direction Drilling (HDD) untuk pemasangan pipa kedalaman 2-3 meter di bawah dasar laut.'},
  // ── 2020 ──
  // ── BARU dari PDF no.6: Lampiran Kantor Cabang BKPM 8 Jan 2020 ──
  {id:'e0new',tanggal:'08 Januari 2020',nomor_surat:'9120305251422',perihal:'Lampiran Kantor Cabang Administrasi',pengirim:'Menteri Investasi / Kepala Badan Koordinasi Penanaman Modal',ringkasan:'Lampiran Kantor Cabang Administrasi untuk PT. Tiara Cipta Nirwana dengan Nomor Induk Berusaha (NIB) 9120305251422. Kantor cabang yang terdaftar berlokasi di Gili Trawangan, Nusa Tenggara Barat, dan dikepalai oleh I Made Gde Putra Yasa. Diterbitkan secara elektronik oleh Menteri Investasi/Kepala BKPM pada 8 Januari 2020. Dokumen hanya berlaku untuk unit administratif perusahaan induk yang berkedudukan di lokasi berbeda. Seluruh data bersumber dari sistem Online Single Submission (OSS), dicetak 01 Oktober 2024.'},
  {id:'e1',tanggal:'13 Januari 2020',nomor_surat:'B-22/MEN-KP/I/2020',perihal:'Penetapan Izin Lokasi Perairan',pengirim:'Menteri Kelautan dan Perikanan RI',ringkasan:'Menteri KKP menerbitkan Izin Lokasi Perairan kepada PT Tiara Cipta Nirwana untuk pemanfaatan air laut di KKPN Gili Ayer, Gili Meno, dan Gili Trawangan. Luasan yang diizinkan 1,09 hektar: area pengambilan 0,47 ha dan pembuangan 0,62 ha. Izin berlaku hingga berakhirnya Izin Usaha, atau 2 tahun jika Izin Usaha belum terbit sejak 13 Januari 2020. Perusahaan wajib melaporkan kegiatan setiap 1 tahun.'},
  {id:'e2',tanggal:'15 Januari 2020',nomor_surat:'-',perihal:'Tagihan PNBP Izin Lokasi Perairan',pengirim:'Kementerian Keuangan RI',ringkasan:'Bukti Pembuatan Tagihan PNBP melalui sistem SIMPONI, Kode Billing 820200115165350, diterbitkan 15 Januari 2020. Total biaya Rp 123.595.000 untuk Izin Lokasi Perairan di TWP Gili Trawangan oleh PT. Tiara Cipta Nirwana. Tagihan akan kedaluwarsa otomatis pada 22 Januari 2020 pukul 10:17:25 WIB.'},
  {id:'e3',tanggal:'16 Januari 2020',nomor_surat:'90E500N9UUS84M56',perihal:'Bukti Penerimaan Negara PNBP',pengirim:'Kementerian Keuangan RI',ringkasan:'Bukti Penerimaan Negara dari sistem SIMPONI Kementerian Keuangan. Pembayaran sebesar Rp123.595.000 disetor oleh Sekretariat Direktorat Jenderal Pengelolaan Ruang Laut untuk PT Tiara Cipta Nirwana. Transaksi melalui teller Bank Mandiri untuk jenis setoran izin lokasi perairan di KKPN TWP Gili Trawangan. Status: sudah dibayar, dicetak 17 Januari 2020.'},
  {id:'e4',tanggal:'07 Februari 2020',nomor_surat:'B.80/MEN-KP/II/2020',perihal:'Rekomendasi Pemanfaatan Pulau Kecil',pengirim:'Menteri Kelautan dan Perikanan RI',ringkasan:'Menteri KKP menerbitkan rekomendasi kepada PT Tiara Cipta Nirwana untuk pemanfaatan lahan 2.925 m2 di Pulau Gili Trawangan. Kegiatan: pengolahan air laut menjadi air minum melalui desalinasi. Rekomendasi berlaku 6 bulan sejak 7 Februari 2020. Perusahaan wajib menjaga ekosistem dan mengalokasikan minimal 30% lahan untuk ruang terbuka hijau.'},
  {id:'e5',tanggal:'05 Agustus 2020',nomor_surat:'05720117200000035',perihal:'Penerbitan Garansi Bank',pengirim:'PT. Bank Rakyat Indonesia (Persero) Tbk',ringkasan:'Garansi Bank No. 05720117200000035 diterbitkan BRI Kantor Cabang Denpasar Gatot Subroto untuk PT. Tiara Cipta Nirwana. Jaminan senilai Rp 7.447.050,00 atas rekomendasi pemanfaatan pulau-pulau kecil di Gili Trawangan kepada KKP. Masa berlaku 6 bulan: 30 Juli 2020 hingga 30 Januari 2021. Bank menjamin pembayaran klaim dalam 14 hari kerja jika terjamin lalai memenuhi kewajiban PNBP.'},
  {id:'e6',tanggal:'13 Agustus 2020',nomor_surat:'503/49/Pem./03/IX/2020',perihal:'Rekomendasi Izin Lokasi dan IMB',pengirim:'Pemerintah Desa Gili Indah',ringkasan:'Rekomendasi kepada PT. Tiara Cipta Nirwana untuk usaha Rumah Produksi Air Bersih di Dusun Gili Trawangan. Izin mencakup Rekomendasi Izin Lokasi dan IMB di lahan 3.115 m2 sesuai SHM No. 575. Pemohon wajib mematuhi Garis Sempadan Bangunan 8 meter dan Garis Sempadan Pagar 4 meter sesuai Perda No. 9 Tahun 2011.'},
  {id:'e7',tanggal:'13 Agustus 2020',nomor_surat:'225/TIARA/VIII/2020',perihal:'Permohonan Izin Mendirikan Bangunan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan IMB oleh Direktur PT TIARA CIPTA NIRWANA kepada Bupati Lombok Utara. Untuk pembangunan Rumah Produksi Air Bersih di Dusun Gili Trawangan, luas lantai 900 m2, status tanah Hak Milik. Dilampirkan rencana anggaran biaya, gambar struktur, dan surat pernyataan tidak keberatan dari tetangga.'},
  {id:'e8',tanggal:'14 Agustus 2020',nomor_surat:'503/24/Pelum/2020',perihal:'Rekomendasi Camat Pemenang',pengirim:'Camat Pemenang, Pemerintah Kabupaten Lombok Utara',ringkasan:'Rekomendasi Camat Pemenang kepada Bupati terkait permohonan izin lokasi dan IMB PT. Tiara Cipta Nirwana. Lokasi Dusun Gili Trawangan, luas tanah 3.115 m2 berdasarkan SHM No. 00575. Pemohon wajib mematuhi Perda No. 9 Tahun 2011 tentang RTRW dan menjaga ketertiban umum.'},
  {id:'e9',tanggal:'18 Agustus 2020',nomor_surat:'230/TIARA/VIII/2020',perihal:'Permohonan Arahan Penyusunan Dokumen Lingkungan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan arahan penyusunan dokumen lingkungan kepada Dinas LHK Provinsi NTB. Rencana kegiatan: pengolahan air laut menjadi air minum menggunakan SWRO di Dusun Gili Trawangan. Merujuk Permen LHK No. P.38/MENLHK/2019 tentang rencana usaha yang wajib AMDAL.'},
  {id:'e10',tanggal:'27 Agustus 2020',nomor_surat:'239/TIARA/VIII/2020',perihal:'Undangan Sosialisasi dan Konsultasi Publik AMDAL',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Undangan pemangku kepentingan untuk sosialisasi dan konsultasi publik pembangunan sarana produksi air bersih di Gili Trawangan. Dilakukan dalam rangka penyusunan studi AMDAL sesuai Permen LHK No. 17 Tahun 2012. Acara Senin, 31 Agustus 2020, pukul 09.00-12.00 WITA di Gili Trawangan.'},
  {id:'e11',tanggal:'September 2020',nomor_surat:'-',perihal:'Penyusunan Kerangka Acuan AMDAL',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Rencana pembangunan sarana produksi air bersih di Gili Trawangan SWRO kapasitas 6.000 m3/hari. Diperlukan pengambilan air laut 16.992 m3/hari melalui pipa intake 500 meter dan pembuangan brine pipa outtake 400 meter. Pelibatan masyarakat melalui pengumuman koran dan konsultasi publik 31 Agustus 2020. Masyarakat berharap harga air kompetitif dan perlindungan ekosistem pesisir.'},
  {id:'e12',tanggal:'17 September 2020',nomor_surat:'260/TIARA/IX/2020',perihal:'Permohonan Addendum Kontrak Ketiga',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan addendum ketiga karena hambatan perizinan di kawasan konservasi Gili Trawangan. Perubahan: kewajiban konstruksi 12 bulan sejak addendum pertama (6 Desember 2019 - 6 Desember 2020). Tarif air Rp 34.000/m3, revisi kenaikan harga dari 8% menjadi 3,5% kumulatif per tahun. Pembayaran minimum 80% dari volume permintaan, denda keterlambatan 0,1% per hari.'},
  {id:'e13',tanggal:'30 September 2020',nomor_surat:'005/2637/PPL-DISLHK/2020',perihal:'Undangan Presentasi Kerangka Acuan AMDAL',pengirim:'Kepala Dinas LHK Provinsi NTB',ringkasan:'Dinas LHK Provinsi NTB mengundang PT Tiara Cipta Nirwana untuk rapat pemeriksaan Formulir Kerangka Acuan (KA) proyek desalinasi Gili Trawangan. Rapat teknis Selasa, 6 Oktober 2020 pukul 09.00 WITA secara daring via Zoom. Ditandatangani Ir. Madani Mukarom selaku Kepala Dinas.'},
  {id:'e14',tanggal:'November 2020',nomor_surat:'308/TIARA/XI/2020',perihal:'Penyerahan Draf Dokumen ANDAL dan RKL RPL',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT. Tiara Cipta Nirwana menyerahkan satu eksemplar draf dokumen ANDAL dan RKL RPL pembangunan sarana produksi air bersih di Gili Indah, Lombok Utara kepada Dinas LHK Provinsi NTB. Perusahaan memohon segera dijadwalkan pembahasan bersama Tim Komisi Penilai AMDAL (KPA) provinsi.'},
  {id:'e15',tanggal:'10 November 2020',nomor_surat:'005/3298/PPL-DISLHK/2020',perihal:'Undangan Presentasi ANDAL dan RKL-RPL',pengirim:'Dinas LHK Provinsi NTB',ringkasan:'Undangan kepada Direktur PT. Tiara Cipta Nirwana untuk rapat presentasi dokumen ANDAL dan RKL-RPL pada Kamis, 26 November 2020 pukul 09.00 WITA via Zoom. Penilaian oleh Tim Teknis dan Komisi Penilai Amdal Provinsi NTB. Ditandatangani Ir. Madani Mukarom.'},
  {id:'e16',tanggal:'21 Desember 2020',nomor_surat:'450/TIARA/XII/2020',perihal:'Permohonan Izin Lingkungan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan Izin Lingkungan kepada Kepala PTSP Provinsi NTB. Direktur I Made Gde Putra Yasa menyertakan delapan jenis dokumen termasuk NPWP, NIB, dan dokumen AMDAL RKL-RPL. Disertakan surat pernyataan keabsahan dokumen No. 451/TIARA/XII/2020 bermeterai Rp 6.000.'},
  {id:'e17',tanggal:'28 Desember 2020',nomor_surat:'503/37-XII/03/IL-AMDAL/DPMPTSP/2020',perihal:'Penetapan Izin Lingkungan',pengirim:'Dinas Penanaman Modal dan PTSP Provinsi NTB',ringkasan:'Penetapan Izin Lingkungan kepada PT. Tiara Cipta Nirwana untuk pembangunan sarana produksi air bersih di Gili Trawangan. Lokasi: area pesisir 13.400 m2, sepadan pantai 150 m2, dan daratan 3.115 m2. Berdasarkan rekomendasi kelayakan lingkungan dari Dinas LHK NTB. Perusahaan wajib mengelola limbah sesuai program NTB Zero Waste dan melaporkan pemantauan lingkungan setiap 6 bulan.'},
  // ── 2021 ──
  {id:'f1',tanggal:'25 Januari 2021',nomor_surat:'600/16/DPU-PR/IMB/2021',perihal:'Pertimbangan Teknis Permohonan IMB',pengirim:'Dinas Pekerjaan Umum dan Penataan Ruang Kabupaten Lombok Utara',ringkasan:'Pertimbangan teknis IMB Rumah Produksi Air Bersih PT. Tiara Cipta Nirwana di Gili Trawangan, luas bangunan 1.096 m2. Nilai retribusi final Rp 12.600.000 dari nilai bangunan Rp 479.400.000. Realisasi Koefisien Dasar Hijau 71,1%, memenuhi syarat minimal 10%. Sempadan bangunan 8 meter, sempadan pagar 4 meter dari as jalan. Berlaku 5 tahun.'},
  {id:'f2',tanggal:'26 Januari 2021',nomor_surat:'-',perihal:'Laporan Proyek KPBU SWRO',pengirim:'PDAM Kabupaten Lombok Utara',ringkasan:'Dokumen menyajikan tahapan lengkap pelaksanaan dan perizinan proyek KPBU penyediaan air bersih melalui teknologi SWRO di Gili Trawangan. Inisiatif badan usaha (unsolicited) oleh PT Tiara Cipta Nirwana yang menandatangani kontrak pada 16 Januari 2018. Mencakup Izin Lokasi Perairan No. B-22/MEN-KP/I/2020 dan SK Kelayakan Lingkungan Hidup No. 503/08 XII/03/SKKL/DPMPTSP/2020. Proses berlanjut hingga 26 Januari 2021 dengan penginputan data IMB ke sistem SIMBG.'},
  {id:'f3',tanggal:'08 Maret 2021',nomor_surat:'B.327/BKKPN/III/2021',perihal:'Evaluasi Pekerjaan Pembangunan SWRO',pengirim:'Balai Kawasan Konservasi Perairan Nasional Kupang',ringkasan:'Evaluasi proyek pembangunan SWRO PT. Tiara Cipta Nirwana di kawasan TWP Gili Matra. Pelaksana belum memiliki Izin Pengelolaan Perairan dari Menteri KKP dan belum berkoordinasi dengan pengelola kawasan. Rekomendasi pemanfaatan 7 Februari 2020 dinyatakan kadaluarsa (sudah melewati 6 bulan). Seluruh aktivitas tidak boleh dilanjutkan sebelum perizinan terpenuhi. Pelaksana diwajibkan berkomitmen restorasi terumbu karang.'},
  {id:'f4',tanggal:'16 Maret 2021',nomor_surat:'03.025/TIARA/III/2021',perihal:'Permohonan Klarifikasi Status IMB',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Klarifikasi IMB Rumah Produksi Air Bersih di Gili Trawangan No. registrasi IMB-520805-04022021-01. Permohonan sejak 3 September 2020 masih berstatus menunggu verifikasi DPMPTSP Kabupaten Lombok Utara. Perusahaan telah menyertakan delapan dokumen persyaratan termasuk izin lokasi, sertifikat tanah, gambar rencana, dan RAB.'},
  {id:'f5',tanggal:'01 April 2021',nomor_surat:'502/93/DTKPMPTSP/IV/2021',perihal:'Klarifikasi Status Permohonan IMB',pengirim:'Dinas Tenaga Kerja, Penanaman Modal dan PTSP Kabupaten Lombok Utara',ringkasan:'Tanggapan klarifikasi kepada PT. Tiara Cipta Nirwana terkait permohonan IMB. Permohonan belum dapat ditindaklanjuti karena belum ada jawaban perbaikan pertimbangan teknis dari Dinas PUPR dan kejelasan mengenai pemasangan jaringan pipa. Belum ada balasan pertimbangan hukum dari Bagian Hukum Setda Kabupaten Lombok Utara. Terdapat Surat Teguran Sekretaris Daerah No. 552/212/APP/2021 tertanggal 26 Maret 2021 mengenai pemberhentian aktivitas di lapangan.'},
  {id:'f6',tanggal:'24 Maret 2021',nomor_surat:'005/115/APP/2017',perihal:'Berita Acara Audiensi Pelelangan KPBU',pengirim:'Bagian Pembangunan Sekretariat Daerah Lombok Utara',ringkasan:'Berita Acara Audiensi mengenai pelelangan Badan Usaha KPBU PDAM Lombok Utara dan PT Tiara Cipta Nirwana, 24 Maret 2021. Panitia lelang tidak memiliki KAK dan HPS sehingga tidak memahami objek lelang secara komprehensif. Terdapat ketidaksesuaian persyaratan SIUP karena tidak mencakup pengelolaan air minum atau desalinasi. Panitia mengakui kekeliruan administratif menandatangani dokumen kualifikasi tanpa verifikasi data.'},
  {id:'f7',tanggal:'07 Mei 2021',nomor_surat:'IMB-520805-04022021-01',perihal:'Pembayaran Retribusi dan Undangan Sidang IMB',pengirim:'Pemerintah Kabupaten Lombok Utara',ringkasan:'Bukti pembayaran retribusi Rp 12.600.000,00 oleh PT Tiara Cipta Nirwana untuk SIMBG/IMB rumah produksi air bersih di Gili Trawangan. Disetor kepada Bendahara Penerima Dinas PTSP Lombok Utara. Surel dari CS SIMBG tanggal 7 Mei 2021 mengenai undangan sidang ulang pada 17 Mei 2021 pukul 08:00 WIB.'},
  {id:'f8',tanggal:'21 Juni 2021',nomor_surat:'539.73/PERUMDA.AM-ADG/VI/2021',perihal:'Peringatan Keterlambatan Pelaksanaan Perjanjian',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung',ringkasan:'Peringatan resmi kepada PT Tiara Cipta Nirwana terkait keterlambatan pelaksanaan perjanjian penyediaan air bersih 2018. PDAM menyatakan addendum perpanjangan waktu konstruksi cacat hukum. PT Tiara dinilai cidera janji karena kewajiban yang seharusnya selesai 16 Januari 2019 belum terpenuhi. Diminta tanggapan paling lambat 5 Juli 2021; jika tidak dipenuhi akan diambil langkah hukum sesuai Pasal 13 perjanjian.'},
  {id:'f9',tanggal:'24 Juni 2021',nomor_surat:'11.115/TIARA/VI/2021',perihal:'Tanggapan Surat Peringatan PERUMDA',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Tanggapan PT Tiara Cipta Nirwana terhadap surat peringatan PERUMDA. Kendala teknis dan perizinan terkait titik pengambilan air baku menjadi penyebab utama keterlambatan, mengakibatkan tiga kali addendum. Meskipun ada hambatan dan pandemi Covid-19, progres pekerjaan saat ini telah mencapai 75%. Perusahaan memohon waktu untuk audiensi klarifikasi.'},
  {id:'f10',tanggal:'09 Agustus 2021',nomor_surat:'LHP.BLL-21080079',perihal:'Laporan Hasil Pengujian Kualitas Udara',pengirim:'Balai Laboratorium Lingkungan Dinas LHK Provinsi NTB',ringkasan:'Laporan hasil pengujian kualitas udara ambien untuk PT Tiara Cipta Nirwana. Sampel diambil 3 Agustus 2021 di dua titik di Gili Trawangan (depan dan belakang area SRO). Pengujian mencakup parameter NO2 dan TSP menggunakan metode SNI dan Portable EPAM. Seluruh parameter berada di bawah ambang batas PP No. 22 Tahun 2021.'},
  {id:'f11',tanggal:'20 September 2021',nomor_surat:'180/1424/PPL-DISLHK/2021',perihal:'Teguran I Laporan RKL-RPL Semester I 2021',pengirim:'Dinas LHK Provinsi NTB',ringkasan:'Teguran I kepada PT. Tiara Cipta Nirwana terkait Laporan Pelaksanaan RKL-RPL periode Semester I 2021. Perusahaan belum melakukan uji kualitas udara dan perairan sesuai matriks rencana pemantauan lingkungan. Diinstruksikan segera melakukan pengujian laboratorium dan menyesuaikan format laporan berdasarkan Kepmen LH No. 45 Tahun 2005. Jika tidak dilaksanakan akan diberikan Teguran II, III, hingga sanksi administratif.'},
  {id:'f12',tanggal:'18 Oktober 2021',nomor_surat:'480/Wil.IV/S/X/2021',perihal:'Permintaan Dokumen Penyelidikan KPPU',pengirim:'KPPU Kantor Wilayah IV',ringkasan:'Tindak lanjut penyelidikan No. 06-392/DH/KPPU.L/VI/2021 mengenai dugaan pelanggaran UU No. 5 Tahun 1999 terkait pengadaan badan usaha penyedia air bersih PDAM Lombok Utara. KPPU meminta laporan keuangan audit 2012-2021 dan akta pendirian. Berkas hardcopy harus dikirimkan ke Kantor Wilayah IV KPPU Surabaya paling lambat 29 Oktober 2021 pukul 12.00 WIB.'},
  {id:'f13',tanggal:'26 Oktober 2021',nomor_surat:'539.137/PERUMDA.AM-ADG/X/2021 dan 14.177/TIARA/X/2021',perihal:'Perjanjian Restrukturisasi Kerjasama',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung dan PT Tiara Cipta Nirwana',ringkasan:'Perjanjian restrukturisasi kerjasama antara PERUMDA Air Minum Amerta Dayan Gunung dan PT Tiara Cipta Nirwana untuk penyediaan air bersih RO. Berlaku 30 tahun, tarif air Rp34.000 per meter kubik untuk kawasan Gili Matra. Permintaan volume air 2.000 m3/hari untuk Gili Meno kemudian dibatalkan Februari 2023. Skema Build-Operate-Transfer (BOT) dengan penyerahan aset di akhir masa kontrak.'},
  {id:'f14',tanggal:'03 November 2021',nomor_surat:'539.147A/PERUMDA.AM-ADG/XI/2021',perihal:'Perjanjian Kerjasama BOT',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung',ringkasan:'Kontrak kerjasama penyediaan air minum teknologi Reverse Osmosis di Gili Trawangan antara PERUMDA ADG dan PT Tiara Cipta Nirwana. Target kapasitas produksi 6.000 m3/hari, masa konstruksi maksimal 12 bulan. Jangka waktu operasional 30 tahun, tarif air Rp 34.000 per meter kubik. Skema Build-Operate-Transfer (BOT): kepemilikan aset diserahkan setelah masa kontrak berakhir.'},
  {id:'f15',tanggal:'10 November 2021',nomor_surat:'529/Wil.IV/S/XI/2021',perihal:'Permintaan Dokumen Kedua KPPU',pengirim:'KPPU Kantor Wilayah IV',ringkasan:'KPPU meminta PT. Tiara Cipta Nirwana menyerahkan dokumen terkait penyelidikan dugaan pelanggaran UU No. 5 Tahun 1999. Dokumen mencakup laporan keuangan 2012-2021, akta pendirian, hingga perjanjian kerja sama. Wajib disampaikan paling lambat 23 November 2021 pukul 12.00 WIB ke Kantor Wilayah IV KPPU Surabaya.'},
  {id:'f16',tanggal:'16 November 2021',nomor_surat:'SK-PBG-520805-16112021-001',perihal:'Penerbitan Persetujuan Bangunan Gedung',pengirim:'Dinas PM PTSP dan Tenaga Kerja Kabupaten Lombok Utara',ringkasan:'Pemerintah Kabupaten Lombok Utara menerbitkan PBG kepada I Made Gde Putra Yasa, 16 November 2021. Untuk Rumah Produksi Air Bersih di Dusun Gili Trawangan, luas bangunan 1.050 m2 di atas tanah 3.115 m2. Rencana teknis memenuhi syarat sesuai UU Bangunan Gedung dan UU Cipta Kerja. Besarnya retribusi: Rp 0.'},
  {id:'f17',tanggal:'16 November 2021',nomor_surat:'06.191/TIARA/XI/2021',perihal:'Penunjukan Pelaksana Distribusi Air',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'PT Tiara Cipta Nirwana menunjuk PT Sarana Tirta Nirwana sebagai pelaksana penyediaan dan distribusi air bersih layak minum teknologi RO di Gili Trawangan. Kewenangan diberikan untuk membuka rekening bersama dengan PERUMDA Air Minum Amerta Dayan Gunung untuk menampung tarif pembayaran pelanggan.'},
  // ── BARU dari PDF no.6: Izin Usaha KKP 20 September 2021 ──
  {id:'f17new',tanggal:'20 September 2021',nomor_surat:'B.469/MEN-KP/IX/2021',perihal:'Izin Usaha Pemanfaatan Air Laut',pengirim:'Menteri Kelautan dan Perikanan Republik Indonesia',ringkasan:'Menteri Kelautan dan Perikanan RI memberikan Izin Usaha Kegiatan Pemanfaatan Air Laut Selain Energi kepada PT. Tiara Cipta Nirwana. Izin mencakup kegiatan penampungan, penjernihan, dan penyaluran air minum di kawasan Gili Indah, Kabupaten Lombok Utara. Lokasi berada di Kawasan Konservasi Perairan Nasional dengan total luas area pemanfaatan 1,09 hektar. Berlaku 10 tahun sejak ditetapkan 20 September 2021. Pemegang izin wajib mematuhi ketentuan pelestarian lingkungan dan melaporkan realisasi kegiatan minimal dua kali dalam setahun.'},
  // ── 2022 ──
  {id:'g1',tanggal:'03 Februari 2022',nomor_surat:'-',perihal:'Laporan Pelaksanaan RKL-RPL Semester II 2021',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Laporan RKL-RPL Semester II 2021 proyek desalinasi SWRO di Gili Trawangan. Kapasitas produksi rata-rata 400 m3/jam atau 6.000 m3/hari. Tahap konstruksi menyerap 188 tenaga kerja, komposisi lokal 57% (107 orang). Kualitas udara ambien dan air laut umumnya memenuhi baku mutu. Catatan: parameter TSS dan karbon monoksida mendekati ambang batas.'},
  {id:'g2',tanggal:'22 April 2022',nomor_surat:'660/1119/PPL-DISLHK/2022',perihal:'Evaluasi Laporan RKL-RPL Tahap Konstruksi',pengirim:'Dinas LHK Provinsi NTB',ringkasan:'Evaluasi laporan RKL-RPL PT. Tiara Cipta Nirwana tahap konstruksi Juli-Desember 2021. Perusahaan wajib menganalisis parameter kecerahan dan TSS yang tidak memenuhi baku mutu pada sampling air laut. Diminta melaksanakan komitmen NTB Hijau: menanam 25 pohon per hektar di area usaha. Laporan perbaikan wajib paling lambat 6 bulan; risiko sanksi administratif jika tidak dipenuhi.'},
  {id:'g3',tanggal:'27 April 2022',nomor_surat:'04.034/TIARA/IV/2022',perihal:'Pemberitahuan Progres Sambungan Rumah',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Pemberitahuan progres penyediaan air bersih layak minum, saat ini kurang lebih 210 sambungan rumah. Produksi air bersih direncanakan mulai 1 Mei 2022, penagihan produksi pelanggan periode 1-14 Juni 2022. Proses masih menunggu Surat Perintah Kerja dari PERUMDAM Amerta Dayan Gunung. Meminta percepatan sosialisasi dan penandatanganan kontrak pelanggan.'},
  {id:'g4',tanggal:'03 Mei 2022',nomor_surat:'539.50A/PERUMDA.AM-ADG/V/2022',perihal:'Berita Acara Operasional Komersial',pengirim:'Perumda Air Minum Amerta Dayan Gunung',ringkasan:'Berita Acara operasional komersial penyediaan air bersih teknologi RO di Gili Trawangan. Unit pengolahan air laut mulai beroperasi 1 Mei 2022, uji coba distribusi gratis hingga 14 Mei 2022. Terhitung 15 Mei 2022, unit dinyatakan resmi beroperasi secara komersial. Merupakan bagian integral dari Perjanjian Restrukturisasi Kerjasama No. 539.137/PERUMDA.AM-ADG/X/2021.'},
  {id:'g5',tanggal:'09 Juni 2022',nomor_surat:'539.79/PERUMDA.AM-ADG/VI/2022',perihal:'Undangan Rapat Koordinasi Operasional',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung',ringkasan:'Undangan resmi kepada Direktur PT Tiara Cipta Nirwana untuk rapat koordinasi operasional produksi air bersih di Gili Trawangan. Pertemuan Senin, 13 Juni 2022 pukul 14.00 WITA di Kantor PERUMDA Air Minum Amerta Dayan Gunung. Ditandatangani Firmansyah, ST selaku Direktur.'},
  {id:'g6',tanggal:'13 September 2022',nomor_surat:'019/02-0881/DPMPTSP/2022',perihal:'Berita Acara Rapat Evaluasi Operasional SPAM',pengirim:'Dinas Penanaman Modal dan PTSP Provinsi NTB',ringkasan:'Berita acara hasil rapat evaluasi penyelenggaraan SPAM oleh PT. Gerbang NTB Emas (GNE) di Gili Trawangan dan Gili Meno. Keputusan utama: penghentian operasional pelayanan air minum oleh PT. GNE mulai 15 Oktober 2022. Pelayanan dialihkan kepada Perumda Air Minum Amerta Dayan Gunung Kabupaten Lombok Utara. DPMPTSP Provinsi NTB berencana mencabut izin pengambilan air tanah PT. GNE setelah menerima kajian hukum.'},
  {id:'g7',tanggal:'19 September 2022',nomor_surat:'B.3561/BKKPN/TU.350/IX/2022',perihal:'Penugasan Monitoring Kawasan Konservasi',pengirim:'Balai Kawasan Konservasi Perairan Nasional Kupang',ringkasan:'BKKPN Kupang menerbitkan surat tugas untuk monitoring di kawasan konservasi Gili Air, Meno, dan Trawangan, 20 September 2022. Tujuh personel ditugaskan mencakup koordinator, analis, fungsional, dan tenaga kontrak. Pelaksana wajib menyampaikan laporan hasil paling lambat satu hari setelah pelaksanaan.'},
  {id:'g8',tanggal:'28 September 2022',nomor_surat:'-',perihal:'Hasil Rapat Pengelolaan Air Gili Tramena',pengirim:'Sekretariat Daerah Provinsi NTB',ringkasan:'Hasil rapat penanganan masalah pengelolaan air bersih di kawasan Gili Tramena, 28 September 2022 di Pendopo Gubernur NTB. Gili Air ditangani langsung PDAM Amerta Dayan Gunung KLU. Gili Meno dan Gili Trawangan melalui kerjasama PDAM dengan PT Berkah Air Laut (PT. BAL) mitra BUMD PT. Gerbang NTB Emas. PT. BAL menyediakan instalasi clean and clear, PDAM bertanggung jawab distribusi operasional.'},
  {id:'g9',tanggal:'03 Oktober 2022',nomor_surat:'660//PPL-DLHK/2022',perihal:'Berita Acara Pembinaan dan Pengawasan Lingkungan',pengirim:'Dinas LHK Provinsi NTB',ringkasan:'Peninjauan lapangan 3 Oktober 2022 terhadap kegiatan desalinasi PT. Tiara Cipta Nirwana di Gili Trawangan. Tim menemukan ketidaksesuaian lokasi pembangunan rumah pompa (14x10,2 m) dan perubahan fungsi lokasi pengambilan menjadi pembuangan. PT. TCN menyepakati perbaikan pengelolaan lingkungan dan penyesuaian izin. Demobilisasi peralatan dan material harus selesai paling lambat Desember 2022.'},
  {id:'g10',tanggal:'07 Oktober 2022',nomor_surat:'03.104/TIARA/X/2022',perihal:'Permohonan Penanganan Kendala Teknis Pengeboran',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan kepada Dinas KKP Provinsi NTB terkait kendala teknis proyek desalinasi Gili Trawangan. Kendala: mata bor hilang dan pipa tersangkut di dasar laut saat teknologi HDD, sehingga posisi pipa bergeser dari koordinat izin awal. Perusahaan mengusulkan pemindahan titik koordinat pengambilan air laut 0,62 ha dan rumah pompa 150 m2. Merujuk Izin Lokasi Perairan No. B-22/MEN-KP/I/2020.'},
  {id:'g11',tanggal:'19 Oktober 2022',nomor_surat:'-',perihal:'Notulen Rapat Persiapan Air Bersih Gili Meno',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung',ringkasan:'Rapat koordinasi 19 Oktober 2022 membahas persiapan pelayanan air bersih di Gili Meno. PERUMDA bermitra dengan PT Tiara Cipta Nirwana dan menyerahkan koordinasi Gili Meno kepada PT TCN untuk dikoordinasikan dengan PT BAL. PT Tiara menyatakan kesiapan kerjasama sesuai regulasi. Dijadwalkan pertemuan PT TCN dan PT BAL pada 24 Oktober 2022 difasilitasi PERUMDA.'},
  {id:'g12',tanggal:'24 Oktober 2022',nomor_surat:'S.863/BPPHLHK-II/TU.PPSA/10/2022',perihal:'Penugasan Verifikasi Lapangan Pelanggaran Lingkungan',pengirim:'Balai Pengamanan dan Penegakan Hukum LHK Jawa Bali Nusa Tenggara',ringkasan:'Penugasan tim verifikasi lapangan terhadap PT Tiara Cipta Nirwana di Lombok Utara atas dugaan pelanggaran konstruksi di sempadan pantai dan perusakan terumbu karang. Pengawasan 26-29 Oktober 2022. Perusahaan diminta menyiapkan dokumen perizinan lingkungan, pengelolaan limbah B3, dan data operasional sesuai checklist.'},
  {id:'g13',tanggal:'02 November 2022',nomor_surat:'B/832/XI/2022/Dit Reskrimsus',perihal:'Permintaan Klarifikasi Dugaan Tindak Pidana',pengirim:'Direktorat Reserse Kriminal Khusus Polda NTB',ringkasan:'Undangan klarifikasi dari Polda NTB kepada Direktur PT Tiara Cipta Nirwana terkait dugaan tindak pidana bidang Sumber Daya Air sesuai UU No. 17 Tahun 2019. Tindak lanjut atas surat permohonan kepastian hukum investasi perusahaan tertanggal 20 Oktober 2022. Penerima diminta hadir menemui penyidik AIPDA I Putu Sukanata pada Rabu, 9 November 2022 pukul 09.00 WITA.'},
  // ── 2023 ──
  {id:'h1',tanggal:'13 Februari 2023',nomor_surat:'11.036/TIARA/II/2023',perihal:'Tanggapan Pembatalan Permintaan Volume Air',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Tanggapan PT Tiara atas surat pembatalan permintaan volume air No. 539.21/PERUMDA.ADG/II/2023 oleh PERUMDA. Perusahaan keberatan karena telah melakukan persiapan lahan dan material untuk pembangunan instalasi. Menyinggung petisi masyarakat Gili Meno yang menginginkan pelayanan air melalui sistem perpipaan bawah laut. Diminta jawaban resmi dalam 7 hari.'},
  {id:'h2',tanggal:'17 Februari 2023',nomor_surat:'TBL/19.a/II/2023/SPKT/POLDA NTB',perihal:'Laporan Dugaan Tindak Pidana Sumber Daya Air',pengirim:'I Gede Agus Artha Guna',ringkasan:'Laporan dugaan tindak pidana bidang Sumber Daya Air ke SPKT POLDA NTB. Terlapor: Samsul Hadi dan William John Matheson, diduga menggunakan sumber daya air tanpa perizinan berusaha untuk kepentingan bisnis. Kejadian di Gili Trawangan dan Gili Meno, 16 Oktober 2018 hingga 1 Desember 2022. Mengacu Pasal 70 huruf c jo Pasal 49 UU No. 17 Tahun 2019 tentang Sumber Daya Air.'},
  {id:'h3',tanggal:'28 April 2023',nomor_surat:'04.087/TIARA/IV/2023',perihal:'Permintaan Penjelasan Pembatalan',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Tindak lanjut PT Tiara kepada PERUMDA mengenai pembatalan permintaan volume air di Gili Meno. Meminta penjelasan rinci alasan pembatalan terkait perjanjian restrukturisasi penyediaan air bersih berbasis RO. Meminta informasi detail petisi masyarakat Gili Meno yang menginginkan air bersih melalui sistem perpipaan bawah laut. Batas waktu jawaban 7 hari. Tembusan kepada Bupati Lombok Utara.'},
  {id:'h4',tanggal:'17 Mei 2023',nomor_surat:'B.376/PSDKP.3/PW.210/V/2023',perihal:'Permintaan Keterangan Pelanggaran Ruang Laut',pengirim:'Direktorat Jenderal Pengawasan Sumber Daya KKP',ringkasan:'KKP mengirim permintaan keterangan kepada PT Tiara Cipta Nirwana terkait indikasi pelanggaran pemanfaatan ruang laut di Kawasan Konservasi Gili Matra. Instalasi pipa bawah laut diduga tidak sesuai koordinat Izin Lokasi Perairan No. B-22/MEN-KP/I/2020. Pertemuan Rabu, 24 Mei 2023 pukul 09:00 WITA di Kantor Dinas KKP Provinsi NTB, Mataram.'},
  {id:'h5',tanggal:'22 Mei 2023',nomor_surat:'B.1370/DJPRL.2/PRL.140/V/2023',perihal:'Arahan Penyesuaian Permohonan KKPRL Baru',pengirim:'Direktorat Jenderal Pengelolaan Ruang Laut KKP',ringkasan:'Arahan kepada PT Tiara Cipta Nirwana untuk penyesuaian izin pemanfaatan ruang laut karena indikasi ketidaksesuaian operasional dengan Izin Lokasi No. B-22/MEN-KP/I/2020. Perusahaan diminta mengembalikan izin lama dan mengajukan Persetujuan KKPRL baru via OSS paling lambat 7 Juni 2023. Persyaratan: rencana bangunan laut, data ekosistem terkini, dan informasi pemanfaatan ruang laut.'},
  {id:'h6',tanggal:'24 Mei 2023',nomor_surat:'-',perihal:'Berita Acara Permintaan Keterangan Polsus KKP',pengirim:'Direktorat Jenderal Pengawasan Sumber Daya KKP',ringkasan:'Berita Acara oleh Polsus PWP3K KKP, 24 Mei 2023, terhadap Project Manager PT Tiara Cipta Nirwana. Klarifikasi atas instalasi pipa di Kawasan Konservasi Pulau Gili yang tidak sesuai izin. Perusahaan menjelaskan kendala teknis pengeboran horizontal Juni 2021 menyebabkan perubahan koordinat. PT TCN telah mengajukan permohonan izin baru via OSS pada 16 Mei 2023, kode KBLI 91039.'},
  {id:'h7',tanggal:'27 Mei 2023',nomor_surat:'03.123/TIARA/V/2023',perihal:'Permohonan Izin Kegiatan Pengeboran',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan izin melanjutkan kegiatan pengeboran penempatan pipa intake air laut di Gili Trawangan yang dihentikan. Penghentian sekitar 3 minggu dikhawatirkan menyebabkan peralatan bor tertanam di bawah dasar laut terjepit. Produksi air baru mencapai 1.500 m3/hari, jauh di bawah kebutuhan 6.000 m3/hari. Merujuk arahan penyesuaian perizinan No. B.1370/DJPRL.2/PRL.140/V/2023.'},
  {id:'h8',tanggal:'17 Juni 2023',nomor_surat:'04.144/TIARA/VI/2023',perihal:'Pengaduan Penghentian Kegiatan Pengeboran',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Laporan penghentian kegiatan pengeboran pipa intake air laut di Gili Trawangan selama sekitar 5 minggu. Pengeboran metode HDD untuk mengejar target 6.000 m3/hari, produksi saat ini baru 1.500 m3/hari. Peralatan bor tertanam di bawah dasar laut berpotensi terjepit. Memohon izin KKP untuk melanjutkan operasional sambil memproses KKPRL baru.'},
  {id:'h9',tanggal:'26 Juni 2023',nomor_surat:'03.150/TIARA/VI/2023',perihal:'Permohonan Rekomendasi Kesesuaian Ruang Laut',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Permohonan rekomendasi persetujuan kesesuaian kegiatan pemanfaatan ruang laut untuk proyek desalinasi. Lokasi di Kawasan Konservasi Taman Wisata Perairan Gili Matra, luas area 1,21 hektare, panjang 2,05 km. Pengolahan menggunakan SWRO pada kedalaman kolom perairan sekitar 15-20 meter. Diajukan sesuai Permen-KP No. 31 Tahun 2020.'},
  {id:'h10',tanggal:'04 Juli 2023',nomor_surat:'539.75/PERUMDA.AM-ADG/VII/2023',perihal:'Teguran Kontinuitas Pasokan Air',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung',ringkasan:'Teguran resmi dari PERUMDA kepada PT. Tiara Cipta Nirwana akibat terganggunya kontinuitas pasokan air di Gili Trawangan. Banyak keluhan pelanggan terutama saat musim puncak wisatawan (high season). PERUMDA meminta perusahaan tidak hanya mengandalkan pasang surut air laut. Merujuk perjanjian kerjasama No. 539.137/PERUMDA.AM-ADG/X/2021.'},
  {id:'h11',tanggal:'07 Juli 2023',nomor_surat:'11.161/TIARA/VII/2023',perihal:'Jawaban Teguran Pasokan Air',pengirim:'PT. Tiara Cipta Nirwana',ringkasan:'Jawaban atas surat teguran PERUMDA 4 Juli 2023 terkait produksi air bersih di Gili Trawangan. Perusahaan berupaya mengoptimalkan metode open intake agar tidak bergantung pada pasang surut. Proses konstruksi mengalami kendala karena aksi penghentian oleh oknum masyarakat. Memohon bantuan dukungan PERUMDA sebagai mitra pemerintah untuk membantu penyelesaian masalah sosial.'},
  {id:'h12',tanggal:'07 Juli 2023',nomor_surat:'005/554/SETDA/2023',perihal:'Undangan Rapat SPAM Gili Meno',pengirim:'Sekretariat Daerah Pemerintah Kabupaten Lombok Utara',ringkasan:'Undangan dari Sekda Kabupaten Lombok Utara untuk membahas rencana pelayanan SPAM oleh PERUMDA Air Minum Amerta Dayan Gunung di Dusun Gili Meno. Pertemuan Rabu, 12 Juli 2023 pukul 14.00 WITA di Ruang Kerja Sekda. Dua belas pihak diundang termasuk Direktur PT. Tiara Cipta Nirwana dan berbagai pejabat daerah.'},
  {id:'h13',tanggal:'17 Juli 2023',nomor_surat:'539.85/PERUMDA.AM-ADG/VII/2023',perihal:'Pengajuan Kembali Permintaan Volume Air RO',pengirim:'PERUMDA Air Minum Amerta Dayan Gunung',ringkasan:'PERUMDA mencabut surat pembatalan permintaan volume SWRO No. 539.21/PERUMDA.AM-ADG/II/2023 tanggal 8 Februari 2023. Secara resmi mengajukan kembali permintaan volume air untuk wilayah Gili Meno sebesar 2000 m3 per hari. Ditandatangani Direktur Firmansyah, ST, 17 Juli 2023.'},
  {id:'h14',tanggal:'25 Juli 2023',nomor_surat:'B.1512/DJPRL.5/PRL.430/VII/2023',perihal:'Jawaban Permohonan Rekomendasi Ruang Laut',pengirim:'Direktorat Jenderal Pengelolaan Ruang Laut KKP',ringkasan:'Tanggapan terhadap permohonan PT. Tiara Cipta Nirwana mengenai rekomendasi pemanfaatan ruang laut di Kawasan Konservasi Nasional Gili Matra yang dikelola berdasarkan Kepmen-KP No. 34 Tahun 2022. Pemanfaatan harus mematuhi PP No. 5 Tahun 2021 dan Permen-KP No. 31/2020. Syarat teknis: wajib memiliki perizinan berusaha KBLI 91039 dan larangan keras dumping dalam kawasan konservasi.'},
  {id:'h15',tanggal:'2023',nomor_surat:'-',perihal:'Permohonan Persetujuan Kesesuaian Kegiatan Pemanfaatan Ruang Laut (PKKPRL)',pengirim:'PT Tiara Cipta Nirwana',ringkasan:'Dokumen permohonan PKKPRL untuk proyek pengolahan air laut berbasis teknologi SWRO di Gili Trawangan. Kapasitas produksi rata-rata 6000 m3/hari. Rencana kegiatan mencakup pipa intake 388,5 meter dan pipa outtake 836 meter menggunakan metode Horizontal Direction Drilling (HDD). Mencakup analisis pemantauan kualitas limbah brine, kondisi hidro-oseanografi, serta perlindungan ekosistem laut termasuk populasi penyu.'},
  // ── 2024 ──
  {id:'i1',tanggal:'14 Mei 2024',nomor_surat:'B.827/BKKPN/TU.330/V/2024',perihal:'Undangan Rapat Penilaian Teknis KKPRL',pengirim:'Balai Kawasan Konservasi Perairan Nasional Kupang',ringkasan:'BKKPN Kupang mengundang rapat penilaian teknis permohonan KKPRL PT. Tiara Cipta Nirwana, 14 Mei 2024. Rapat Jumat, 17 Mei 2024 via Zoom Cloud Meeting membahas penempatan pipa intake dan outtake pengolahan air laut di Perairan Gili Trawangan. Undangan ditujukan kepada pemangku kepentingan termasuk perwakilan kementerian, pemerintah daerah, dan akademisi Universitas Mataram.'},
  {id:'i2',tanggal:'08 Mei 2024',nomor_surat:'-',perihal:'Berita Acara Permintaan Keterangan KKP',pengirim:'Kementerian Kelautan dan Perikanan',ringkasan:'Permintaan keterangan terkait indikasi pelanggaran pemanfaatan ruang laut oleh PT Tiara Cipta Nirwana di Kawasan Konservasi Gili Trawangan. I Gede Agus Artha Guna selaku Manajer Operasional mengakui pengeboran dimulai 20 April 2024 meskipun dokumen PKKPRL untuk luasan 0,081 hektar masih dalam proses verifikasi di oss.go.id. Kegiatan pengeboran menggunakan bahan bentonite dan filtrol yang mengakibatkan sebaran lumpur dan komplain masyarakat. Perusahaan dikenakan denda administratif Rp4.539.240 dan berkomitmen menghentikan pengeboran sementara hingga dokumen perizinan diterbitkan.'},
  {id:'i3',tanggal:'06 Juni 2024',nomor_surat:'/PSDKPLan.4/PW.210/VI/2024',perihal:'Berita Acara Penghentian Pelanggaran',pengirim:'Pangkalan PSDKP Benoa, Kementerian Kelautan dan Perikanan',ringkasan:'Penghentian pelanggaran pemanfaatan air laut oleh PT. TIARA CIPTA NIRWANA di KKPN Gili Trawangan pada 6 Juni 2024 pukul 13.00 WITA. Dihentikan oleh Pangkalan PSDKP Benoa karena belum memiliki dokumen PKKPRL sesuai aturan yang berlaku. Pelaku usaha diwajibkan menghentikan seluruh aktivitas pemanfaatan air laut selain energi hingga dokumen resmi diterbitkan. Ditandatangani tiga petugas Polsus PWP3K, penanggung jawab usaha, dan saksi-saksi di lapangan.'},
  {id:'i4',tanggal:'06 Juni 2024',nomor_surat:'-',perihal:'Berita Acara Verifikasi Lapangan Lingkungan',pengirim:'Dinas Lingkungan Hidup dan Kehutanan Provinsi NTB',ringkasan:'Berita Acara Verifikasi Lapangan 6 Juni 2024 terkait dugaan pencemaran lingkungan oleh PT. Tiara Cipta Nirwana di Dusun Gili Trawangan. Tim verifikasi dari DLHK Provinsi NTB menemukan perusahaan telah memiliki izin lengkap termasuk Persetujuan Teknis Pembuangan Air Limbah No. 660/1247/PSPP-DISLHK/2023. Hasil pemeriksaan fisik menunjukkan tidak adanya tanda-tanda pencemaran, semburan lumpur, atau endapan sedimen pada titik-titik yang dicurigai.'},
];

export { MONTHS_MAP, parseDateKey, getYear, CAT_LABELS, categorize, DOCS }
